/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package posseblakratu.view;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.ui.FlatLineBorder;
import java.awt.Color;
import java.awt.Insets;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import posseblakratu.config.Koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/**
 *
 * @author Al
 */
public final class FrameLogin extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameLogin.class.getName());

    /** Creates new form FrameLogin */
    public FrameLogin() {
        initComponents();
        
        //memanggil panel melengkung pada setiap panel yg di lengkungkan
        panelLengkung(usrContainer); 
        panelLengkung(passContainer);
        panelLengkung(roleContainer);
        
        
     
        tPassword.setEchoChar((char) 0); // placeholder dibuat jadi terlihat
        tPassword.setText("Masukkan Password"); //placehokder bertuliskan masukkan password
        

        
    }
    
    //method untuk mengatur style panel agar terlihat melengkung
    //menerapkan border dengan warna dan radius tertentu
    void panelLengkung(JPanel p) {

        //mengatur border panel utama yang dikirim sebagai parameter
        p.setBorder(new FlatLineBorder(
                new Insets(0, 0, 0, 0),
                Color.decode("#E7BDBB"),
                1f,
                10));

        //mengatur border container login agar lebih melengkung
        containerLogin.setBorder(new FlatLineBorder(
                new Insets(0, 0, 0, 0),
                Color.decode("#E7BDBB"),
                1f,
                20));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new javax.swing.JPanel();
        rightContainer = new javax.swing.JPanel();
        containerLogin = new javax.swing.JPanel();
        jJpanelll = new javax.swing.JPanel();
        usrContainer = new javax.swing.JPanel();
        tUsername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Jpanell = new javax.swing.JPanel();
        lblPassword = new javax.swing.JLabel();
        passContainer = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tPassword = new javax.swing.JPasswordField();
        btnMata = new javax.swing.JToggleButton();
        Jpanelll = new javax.swing.JPanel();
        lblMasukSebagai = new javax.swing.JLabel();
        roleContainer = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cRole = new javax.swing.JComboBox<>();
        lblUsernameLogin = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        txtCopyright = new javax.swing.JLabel();
        leftContainer = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblToko = new javax.swing.JLabel();
        tDetail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));

        mainPanel.setBackground(new java.awt.Color(252, 249, 255));
        mainPanel.setMinimumSize(new java.awt.Dimension(1280, 720));
        mainPanel.setPreferredSize(new java.awt.Dimension(1280, 720));
        mainPanel.setLayout(new java.awt.GridBagLayout());

        rightContainer.setBackground(new java.awt.Color(252, 249, 255));
        rightContainer.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 22));

        containerLogin.setBackground(new java.awt.Color(255, 255, 255));
        containerLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 189, 187)));

        jJpanelll.setBackground(new java.awt.Color(255, 255, 255));
        jJpanelll.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usrContainer.setBackground(new java.awt.Color(255, 255, 255));
        usrContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 189, 187)));

        tUsername.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 16)); // NOI18N
        tUsername.setBorder(null);
        tUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tUsernameFocusLost(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new FlatSVGIcon("posseblakratu/icon/IconUsr.svg")
        );

        javax.swing.GroupLayout usrContainerLayout = new javax.swing.GroupLayout(usrContainer);
        usrContainer.setLayout(usrContainerLayout);
        usrContainerLayout.setHorizontalGroup(
            usrContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usrContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addContainerGap())
        );
        usrContainerLayout.setVerticalGroup(
            usrContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usrContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(usrContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jJpanelll.add(usrContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, -1));

        Jpanell.setBackground(new java.awt.Color(255, 255, 255));
        Jpanell.setAlignmentX(1.0F);
        Jpanell.setAlignmentY(1.0F);

        lblPassword.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        lblPassword.setText("Password");

        passContainer.setBackground(new java.awt.Color(255, 255, 255));
        passContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 189, 187)));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new FlatSVGIcon("posseblakratu/icon/IconPass.svg")
        );

        tPassword.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 16)); // NOI18N
        tPassword.setBorder(null);
        tPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tPasswordFocusLost(evt);
            }
        });

        btnMata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posseblakratu/icon/IconMata.png"))); // NOI18N
        btnMata.setBorder(null);
        btnMata.setContentAreaFilled(false);
        btnMata.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/posseblakratu/icon/IconMata.png"))); // NOI18N
        btnMata.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/posseblakratu/icon/DisIconMata2.png"))); // NOI18N
        btnMata.addActionListener(this::btnMataActionPerformed);

        javax.swing.GroupLayout passContainerLayout = new javax.swing.GroupLayout(passContainer);
        passContainer.setLayout(passContainerLayout);
        passContainerLayout.setHorizontalGroup(
            passContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMata, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        passContainerLayout.setVerticalGroup(
            passContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(passContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(tPassword))
                .addContainerGap())
            .addComponent(btnMata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout JpanellLayout = new javax.swing.GroupLayout(Jpanell);
        Jpanell.setLayout(JpanellLayout);
        JpanellLayout.setHorizontalGroup(
            JpanellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(passContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JpanellLayout.setVerticalGroup(
            JpanellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanellLayout.createSequentialGroup()
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        Jpanelll.setBackground(new java.awt.Color(255, 255, 255));
        Jpanelll.setAlignmentX(1.0F);
        Jpanelll.setAlignmentY(1.0F);

        lblMasukSebagai.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        lblMasukSebagai.setText("Masuk Sebagai");

        roleContainer.setBackground(new java.awt.Color(255, 255, 255));
        roleContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 189, 187)));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new FlatSVGIcon("posseblakratu/icon/IconRole.svg")
        );

        cRole.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 16)); // NOI18N
        cRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kasir", "Owner" }));
        cRole.setBorder(null);

        javax.swing.GroupLayout roleContainerLayout = new javax.swing.GroupLayout(roleContainer);
        roleContainer.setLayout(roleContainerLayout);
        roleContainerLayout.setHorizontalGroup(
            roleContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roleContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cRole, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        roleContainerLayout.setVerticalGroup(
            roleContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roleContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roleContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(cRole))
                .addContainerGap())
        );

        javax.swing.GroupLayout JpanelllLayout = new javax.swing.GroupLayout(Jpanelll);
        Jpanelll.setLayout(JpanelllLayout);
        JpanelllLayout.setHorizontalGroup(
            JpanelllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMasukSebagai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(roleContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JpanelllLayout.setVerticalGroup(
            JpanelllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelllLayout.createSequentialGroup()
                .addComponent(lblMasukSebagai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roleContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        lblUsernameLogin.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        lblUsernameLogin.setText("Username");

        btnLogin.setBackground(new java.awt.Color(214, 4, 39));
        btnLogin.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 16)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setIcon(new FlatSVGIcon("posseblakratu/icon/IconLogin.svg")
        );
        btnLogin.setText("Login");
        btnLogin.setBorderPainted(false);
        btnLogin.setFocusPainted(false);
        btnLogin.setFocusable(false);
        btnLogin.addActionListener(this::btnLoginActionPerformed);

        javax.swing.GroupLayout containerLoginLayout = new javax.swing.GroupLayout(containerLogin);
        containerLogin.setLayout(containerLoginLayout);
        containerLoginLayout.setHorizontalGroup(
            containerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLoginLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(containerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jJpanelll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Jpanell, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Jpanelll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUsernameLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        containerLoginLayout.setVerticalGroup(
            containerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLoginLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblUsernameLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jJpanelll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(Jpanell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(Jpanelll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        rightContainer.add(containerLogin);

        txtCopyright.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        txtCopyright.setForeground(new java.awt.Color(92, 62, 60));
        txtCopyright.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCopyright.setText("© 2026 Ratu Seblak POS System. All rights reserved.");
        txtCopyright.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rightContainer.add(txtCopyright);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = -298;
        gridBagConstraints.ipady = 61;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(110, 70, 130, 200);
        mainPanel.add(rightContainer, gridBagConstraints);

        leftContainer.setBackground(new java.awt.Color(252, 249, 255));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posseblakratu/icon/logo.png"))); // NOI18N
        lblLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        leftContainer.add(lblLogo);

        lblToko.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 40)); // NOI18N
        lblToko.setForeground(new java.awt.Color(214, 4, 39));
        lblToko.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblToko.setText("RATU SEBLAK");
        leftContainer.add(lblToko);

        tDetail.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        tDetail.setForeground(new java.awt.Color(92, 62, 60));
        tDetail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tDetail.setText("Sistem Point of Sale");
        leftContainer.add(tDetail);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -254;
        gridBagConstraints.ipady = 81;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(220, 190, 100, 0);
        mainPanel.add(leftContainer, gridBagConstraints);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMataActionPerformed
        // TODO add your handling code here:
        
        // membuat logika icon mata, jika icon mata klik maka teks akan terlihat
        if (btnMata.isSelected()) {
            // Password terlihat
            tPassword.setEchoChar((char) 0);
        } else {
            // Password disembunyikan
            tPassword.setEchoChar('•');
        }
    }//GEN-LAST:event_btnMataActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:

        //ambil teks yg dimasukkan user pada field username 
        String username = tUsername.getText();

        //ambil teks yg dimasukkan user pada field password
        String password = String.valueOf(tPassword.getPassword());

        //ambil role yang dipilih pada combobox
        String role = cRole.getSelectedItem().toString();

        //periksa apakah username dan password tidak kosong
        if (username.length() != 0 && password.length() != 0) {
            try {
                //query sql utk mencari user dengan username, password dan role
                String sql = "SELECT * FROM pengguna WHERE username=? AND password=MD5(?) AND role=? AND status='Aktif'";

                //membuat koneksi ke database
                Connection con = Koneksi.konek();

                //siapkan statement sql dgn parameter
                PreparedStatement ps = con.prepareStatement(sql);

                //isi parameter pertama (?) dgn username
                ps.setString(1, username);

                //isi parameter kedua (?) dgn password yg akan di hash MD5
                ps.setString(2, password);

                //isi parameter ketiga (?) dgn role
                ps.setString(3, role);

                //jalankan query dan ambil hasilnya
                ResultSet rs = ps.executeQuery();

                //jika hasil query memiliki hasil (berarti login berhasil)
                if (rs.next()) {

                    //tutup form login
                    dispose();

                    //cek role untuk membuka frame yang sesuai
                    if (role.equals("Kasir")) {

                        new FrameKasir().setVisible(true);

                    } else if (role.equals("Owner")) {

                        new FrameOwner().setVisible(true);

                    }

                } else {
                    //jika data tdk ditemukan, tampilkan pesan error
                    JOptionPane.showMessageDialog(null, "Username/Password/Role salah");
                }

            } catch (SQLException sQLException) {
                //jika terjadi kesalahan sql, tampilkan pesan error
                JOptionPane.showMessageDialog(null, sQLException.getMessage());
            }
        } else {
            //jika username / password kosong, beri peringatan ke user
            JOptionPane.showMessageDialog(null, "Username/password tidak boleh kosong");
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void tUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tUsernameFocusGained
        // TODO add your handling code here:
        // focus gained aktif ketika pengguna mengklik atau mengarahkan kursor ke dalam field text
        // mengambil teks yang saat ini ada di dalam kolom tUsername
        String username = tUsername.getText();
        // memeriksa apakah teks di dalam kolom masih berupa tulisan placeholder ("Masukkan Username")
        if(username.equals("Masukkan Username")){
            // jika benar masih placeholder, kosongkan kolom agar pengguna bisa langsung mengetik
            tUsername.setText("");
        }
    }//GEN-LAST:event_tUsernameFocusGained

    private void tUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tUsernameFocusLost
        // TODO add your handling code here:
        // Memeriksa apakah kolom dalam keadaan kosong atau memang teksnya masih placeholder
        String username = tUsername.getText();
        if(username.equals("")||username.equals("Masukkan Username")){
            // Jika kosong, kembalikan tulisan placeholder
            tUsername.setText("Masukkan Username");
        }
    }//GEN-LAST:event_tUsernameFocusLost

    private void tPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tPasswordFocusGained
        // TODO add your handling code here:
        // Mengambil teks password dan mengubahnya dari bentuk char[] menjadi String
        String password = String.valueOf(tPassword.getPassword());
        
        // Memeriksa apakah teks di dalam kolom adalah placeholder ("Masukkan Password")
        if (password.equals("Masukkan Password")) {
            // Jika benar, kosongkan kolom agar siap menerima input dari pengguna
            tPassword.setText("");
            // Aktifkan karakter penyamat (bullet '•') agar password yang diketik bersifat rahasia/bintang-bintang
            tPassword.setEchoChar('•');
        }

    }//GEN-LAST:event_tPasswordFocusGained

    private void tPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tPasswordFocusLost
        // TODO add your handling code here:
        // Mengambil teks password saat ini untuk dicek
        String password = String.valueOf(tPassword.getPassword());

        // Memeriksa apakah pengguna membiarkan kolom password ini kosong (tidak mengetik apa pun)
        if (password.isEmpty()) {
            // Matikan fungsi echo char (diubah ke angka 0) agar teks placeholder bisa terbaca normal (bukan berupa titik-titik)
            tPassword.setEchoChar((char) 0);
            // Tampilkan kembali teks petunjuk placeholder-nya
            tPassword.setText("Masukkan Password");
        }

    }//GEN-LAST:event_tPasswordFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.put("ComboBox.selectionBackground", new java.awt.Color(252,232,230)); //memgatur warna selection backround di combo box
            UIManager.put("ComboBox.selectionForeground", new java.awt.Color(0,0,0)); //mengatur warna teks / foreground di selection combo box
            UIManager.put("Button.arc", 10); //membaut button melengkung
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException unsupportedLookAndFeelException) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jpanell;
    private javax.swing.JPanel Jpanelll;
    private javax.swing.JButton btnLogin;
    private javax.swing.JToggleButton btnMata;
    private javax.swing.JComboBox<String> cRole;
    private javax.swing.JPanel containerLogin;
    private javax.swing.JPanel jJpanelll;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMasukSebagai;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblToko;
    private javax.swing.JLabel lblUsernameLogin;
    private javax.swing.JPanel leftContainer;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel passContainer;
    private javax.swing.JPanel rightContainer;
    private javax.swing.JPanel roleContainer;
    private javax.swing.JLabel tDetail;
    private javax.swing.JPasswordField tPassword;
    private javax.swing.JTextField tUsername;
    private javax.swing.JLabel txtCopyright;
    private javax.swing.JPanel usrContainer;
    // End of variables declaration//GEN-END:variables

}
