/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package posseblakratu.view;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Al
 */
public final class FrameOwner extends javax.swing.JFrame {
    CardLayout page;

    /**
     * Creates new form FrameUtama
     */
    public FrameOwner() {
        initComponents();
        
        
        TanggalJam(); //memanggil method waktu
        
        inisiasiPanel(); //memanggil method inisiasi panel
        
        btnTransaksi.setSelected(true); //membuat btnTransaksi bernilai true/selected 
        stateSidebar(btnTransaksi); //memanggil state button sidebar untuk btnTransaksi
    }
    
    
    //method untuk menginisiasi panel
    void inisiasiPanel(){
        page = (CardLayout)contentPanel.getLayout();
        contentPanel.add(new PanelDiskon(), "diskon");
        contentPanel.add(new PanelLaporan(), "laporan");
        contentPanel.add(new PanelPengguna(), "pengguna");
        contentPanel.add(new PanelProduk(), "produk");
        contentPanel.add(new PanelStok(), "stok");
        contentPanel.add(new PanelTransaksi(), "transaksi");
    }


    
    
    //method untuk menampilkan tanggal dan jam pada header
    private void TanggalJam() {

        //membuat timer yang berjalan setiap 1 detik
        javax.swing.Timer timer = new javax.swing.Timer(1000, (java.awt.event.ActionEvent e) -> {

            //mengatur locale ke bahasa Indonesia
            java.util.Locale localeIndonesia = new java.util.Locale("id", "ID");

            //mengatur format tanggal dan jam
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat(
                    "EEEE, dd MMMM yyyy | HH.mm",
                    localeIndonesia
            );

            //mengambil tanggal dan jam saat ini
            String waktu = sdf.format(new java.util.Date());

            //menampilkan tanggal dan jam pada label
            lblTanggalJam.setText(waktu);
        });

        //menjalankan timer
        timer.start();
    }
    
    
    
    

    
    
    
    
    //method utk state aktif dan nonaktif untuk sidebar
    private void stateSidebar(javax.swing.JToggleButton tombol) {
        tombol.setUI(new javax.swing.plaf.basic.BasicToggleButtonUI());

        //margin kiri
        javax.swing.border.Border marginKiri = javax.swing.BorderFactory.createEmptyBorder(0, 23, 0, 0);

        if (tombol.isSelected()) {
            //state aktif
            tombol.setBackground(new java.awt.Color(255, 237, 213));
            tombol.setForeground(new java.awt.Color(234, 88, 12));

            javax.swing.border.Border garisOren = javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 4, new java.awt.Color(234, 88, 12));
            tombol.setBorder(javax.swing.BorderFactory.createCompoundBorder(garisOren, marginKiri));
        } else {
            //state nonaktif
            tombol.setBackground(java.awt.Color.WHITE);
            tombol.setForeground(new java.awt.Color(100, 116, 139));

            javax.swing.border.Border garisPutih = javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 4, java.awt.Color.WHITE);
            tombol.setBorder(javax.swing.BorderFactory.createCompoundBorder(garisPutih, marginKiri));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupButtonSidebar = new javax.swing.ButtonGroup();
        headerPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        containerTxtHeader = new javax.swing.JPanel();
        lblToko = new javax.swing.JLabel();
        txtPosSystem = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblTanggalJam = new javax.swing.JLabel();
        sidebarPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        btnSetting = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnTransaksi = new javax.swing.JToggleButton();
        btnProduk = new javax.swing.JToggleButton();
        btnStok = new javax.swing.JToggleButton();
        btnPengguna = new javax.swing.JToggleButton();
        btnDiskon = new javax.swing.JToggleButton();
        btnLaporan = new javax.swing.JToggleButton();
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));

        headerPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        headerPanel.setPreferredSize(new java.awt.Dimension(1280, 80));
        headerPanel.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(204, 204, 204)));
        jPanel3.setMinimumSize(new java.awt.Dimension(205, 80));
        jPanel3.setPreferredSize(new java.awt.Dimension(205, 80));

        containerTxtHeader.setBackground(new java.awt.Color(255, 255, 255));
        containerTxtHeader.setLayout(new java.awt.BorderLayout());

        lblToko.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 20)); // NOI18N
        lblToko.setForeground(new java.awt.Color(186, 27, 27));
        lblToko.setText("SEBLAK RATU");
        containerTxtHeader.add(lblToko, java.awt.BorderLayout.CENTER);

        txtPosSystem.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        txtPosSystem.setForeground(new java.awt.Color(72, 86, 106));
        txtPosSystem.setText("POS System");
        txtPosSystem.setAlignmentY(0.0F);
        containerTxtHeader.add(txtPosSystem, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(containerTxtHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(containerTxtHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        headerPanel.add(jPanel3, java.awt.BorderLayout.LINE_START);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setMinimumSize(new java.awt.Dimension(1075, 80));
        jPanel4.setPreferredSize(new java.awt.Dimension(1075, 80));

        lblTanggalJam.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 16)); // NOI18N
        lblTanggalJam.setForeground(new java.awt.Color(72, 86, 106));
        lblTanggalJam.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTanggalJam.setText("Sabtu, 25 April 2026 | 18.00");
        lblTanggalJam.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblTanggalJam.setPreferredSize(new java.awt.Dimension(1001, 24));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(lblTanggalJam, javax.swing.GroupLayout.PREFERRED_SIZE, 983, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblTanggalJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        headerPanel.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(headerPanel, java.awt.BorderLayout.PAGE_START);

        sidebarPanel.setBackground(new java.awt.Color(255, 255, 255));
        sidebarPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(204, 204, 204)));
        sidebarPanel.setMinimumSize(new java.awt.Dimension(205, 640));
        sidebarPanel.setPreferredSize(new java.awt.Dimension(205, 640));
        sidebarPanel.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(204, 204, 204)));
        jPanel1.setPreferredSize(new java.awt.Dimension(205, 121));
        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        btnLogout.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 16)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(100, 116, 139));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posseblakratu/icon/IconLogout.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 23, 1, 1));
        btnLogout.setContentAreaFilled(false);
        btnLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLogout.setIconTextGap(14);
        btnLogout.addActionListener(this::btnLogoutActionPerformed);
        jPanel1.add(btnLogout);

        btnSetting.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 16)); // NOI18N
        btnSetting.setForeground(new java.awt.Color(100, 116, 139));
        btnSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posseblakratu/icon/IconSetting.png"))); // NOI18N
        btnSetting.setText("Pengaturan");
        btnSetting.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 23, 1, 1));
        btnSetting.setContentAreaFilled(false);
        btnSetting.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSetting.setIconTextGap(14);
        btnSetting.addActionListener(this::btnSettingActionPerformed);
        jPanel1.add(btnSetting);

        sidebarPanel.add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(14, 0, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(204, 355));
        jPanel2.setRequestFocusEnabled(false);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.GridLayout(6, 1));

        grupButtonSidebar.add(btnTransaksi);
        btnTransaksi.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 16)); // NOI18N
        btnTransaksi.setForeground(new java.awt.Color(100, 116, 139));
        btnTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posseblakratu/icon/DisIconTrx.png"))); // NOI18N
        btnTransaksi.setText("Transaksi");
        btnTransaksi.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 23, 0, 4));
        btnTransaksi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTransaksi.setIconTextGap(14);
        btnTransaksi.setMargin(new java.awt.Insets(2, 90, 3, 14));
        btnTransaksi.setSelectedIcon(new FlatSVGIcon("posseblakratu/icon/IconTrx.svg"));
        btnTransaksi.addItemListener(this::btnTransaksiItemStateChanged);
        btnTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseExited(evt);
            }
        });
        jPanel5.add(btnTransaksi);

        grupButtonSidebar.add(btnProduk);
        btnProduk.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 16)); // NOI18N
        btnProduk.setForeground(new java.awt.Color(100, 116, 139));
        btnProduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posseblakratu/icon/DisIconProduk.png"))); // NOI18N
        btnProduk.setText("Produk");
        btnProduk.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 23, 0, 3));
        btnProduk.setContentAreaFilled(false);
        btnProduk.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProduk.setIconTextGap(14);
        btnProduk.setMargin(new java.awt.Insets(2, 90, 3, 14));
        btnProduk.setOpaque(true);
        btnProduk.setSelectedIcon(new FlatSVGIcon("posseblakratu/icon/IconProduk.svg"));
        btnProduk.addItemListener(this::btnProdukItemStateChanged);
        jPanel5.add(btnProduk);

        grupButtonSidebar.add(btnStok);
        btnStok.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 16)); // NOI18N
        btnStok.setForeground(new java.awt.Color(100, 116, 139));
        btnStok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posseblakratu/icon/DisIconStok.png"))); // NOI18N
        btnStok.setText("Stok");
        btnStok.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 23, 0, 3));
        btnStok.setContentAreaFilled(false);
        btnStok.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnStok.setIconTextGap(14);
        btnStok.setMargin(new java.awt.Insets(2, 90, 3, 14));
        btnStok.setOpaque(true);
        btnStok.setSelectedIcon(new FlatSVGIcon("posseblakratu/icon/IconStok.svg"));
        btnStok.addItemListener(this::btnStokItemStateChanged);
        jPanel5.add(btnStok);

        grupButtonSidebar.add(btnPengguna);
        btnPengguna.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 16)); // NOI18N
        btnPengguna.setForeground(new java.awt.Color(100, 116, 139));
        btnPengguna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posseblakratu/icon/DisIconPengguna.png"))); // NOI18N
        btnPengguna.setText("Pengguna");
        btnPengguna.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 23, 0, 3));
        btnPengguna.setContentAreaFilled(false);
        btnPengguna.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPengguna.setIconTextGap(14);
        btnPengguna.setMargin(new java.awt.Insets(2, 90, 3, 14));
        btnPengguna.setOpaque(true);
        btnPengguna.setSelectedIcon(new FlatSVGIcon("posseblakratu/icon/IconPengguna.svg"));
        btnPengguna.addItemListener(this::btnPenggunaItemStateChanged);
        jPanel5.add(btnPengguna);

        grupButtonSidebar.add(btnDiskon);
        btnDiskon.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 16)); // NOI18N
        btnDiskon.setForeground(new java.awt.Color(100, 116, 139));
        btnDiskon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posseblakratu/icon/DisIconDiskon.png"))); // NOI18N
        btnDiskon.setText("Diskon");
        btnDiskon.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 23, 0, 3));
        btnDiskon.setContentAreaFilled(false);
        btnDiskon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDiskon.setIconTextGap(14);
        btnDiskon.setMargin(new java.awt.Insets(2, 90, 3, 14));
        btnDiskon.setOpaque(true);
        btnDiskon.setSelectedIcon(new FlatSVGIcon("posseblakratu/icon/IconDiskon.svg"));
        btnDiskon.addItemListener(this::btnDiskonItemStateChanged);
        btnDiskon.addActionListener(this::btnDiskonActionPerformed);
        jPanel5.add(btnDiskon);

        grupButtonSidebar.add(btnLaporan);
        btnLaporan.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 16)); // NOI18N
        btnLaporan.setForeground(new java.awt.Color(100, 116, 139));
        btnLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posseblakratu/icon/DisIconLaporan.png"))); // NOI18N
        btnLaporan.setText("Laporan");
        btnLaporan.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 23, 0, 3));
        btnLaporan.setContentAreaFilled(false);
        btnLaporan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLaporan.setIconTextGap(14);
        btnLaporan.setMargin(new java.awt.Insets(2, 90, 3, 14));
        btnLaporan.setOpaque(true);
        btnLaporan.setSelectedIcon(new FlatSVGIcon("posseblakratu/icon/IconLaporan.svg"));
        btnLaporan.addItemListener(this::btnLaporanItemStateChanged);
        jPanel5.add(btnLaporan);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
        );

        sidebarPanel.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(sidebarPanel, java.awt.BorderLayout.LINE_START);

        contentPanel.setMinimumSize(new java.awt.Dimension(1075, 640));
        contentPanel.setPreferredSize(new java.awt.Dimension(1075, 640));
        contentPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(contentPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTransaksiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnTransaksiItemStateChanged
        // TODO add your handling code here:
        stateSidebar(btnTransaksi); //memanggil method state aktif dan nonaktif tombol di event state change
        page.show(contentPanel, "transaksi"); //memanggil method inisiasi panel
        
    }//GEN-LAST:event_btnTransaksiItemStateChanged

    private void btnLaporanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnLaporanItemStateChanged
        // TODO add your handling code here:
        stateSidebar(btnLaporan);
        page.show(contentPanel, "laporan");
    }//GEN-LAST:event_btnLaporanItemStateChanged

    private void btnProdukItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnProdukItemStateChanged
        // TODO add your handling code here:
        stateSidebar(btnProduk);
        page.show(contentPanel, "produk");

    }//GEN-LAST:event_btnProdukItemStateChanged

    private void btnStokItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnStokItemStateChanged
        // TODO add your handling code here:
        stateSidebar(btnStok);
        page.show(contentPanel, "stok");
    }//GEN-LAST:event_btnStokItemStateChanged

    private void btnPenggunaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnPenggunaItemStateChanged
        // TODO add your handling code here:
        stateSidebar(btnPengguna);
        page.show(contentPanel, "pengguna");
    }//GEN-LAST:event_btnPenggunaItemStateChanged

    private void btnDiskonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnDiskonItemStateChanged
        // TODO add your handling code here:
        stateSidebar(btnDiskon);
        page.show(contentPanel, "diskon");
    }//GEN-LAST:event_btnDiskonItemStateChanged

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        
        int pilihan = JOptionPane.showConfirmDialog(
                null,
                "Apakah Anda yakin ingin keluar?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION);

        switch (pilihan) {
            case JOptionPane.YES_OPTION -> {
                dispose();
                new FrameLogin().setVisible(true);
            }
            case JOptionPane.NO_OPTION -> {
            }
            default -> {
            }
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingActionPerformed
        // TODO add your handling code here:
        new FramePengaturan().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSettingActionPerformed

    private void btnTransaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTransaksiMouseEntered

    private void btnTransaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTransaksiMouseExited

    private void btnDiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiskonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDiskonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
       
        try {
            UIManager.put("Button.arc", 10);
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException unsupportedLookAndFeelException) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameOwner().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnDiskon;
    private javax.swing.JToggleButton btnLaporan;
    private javax.swing.JButton btnLogout;
    private javax.swing.JToggleButton btnPengguna;
    private javax.swing.JToggleButton btnProduk;
    private javax.swing.JButton btnSetting;
    private javax.swing.JToggleButton btnStok;
    private javax.swing.JToggleButton btnTransaksi;
    private javax.swing.JPanel containerTxtHeader;
    private javax.swing.JPanel contentPanel;
    private javax.swing.ButtonGroup grupButtonSidebar;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblTanggalJam;
    private javax.swing.JLabel lblToko;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JLabel txtPosSystem;
    // End of variables declaration//GEN-END:variables
}
