/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package posseblakratu.view;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.ui.FlatLineBorder;
import java.awt.Color;
import java.awt.Insets;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;


/**
 *
 * @author Al
 */
public final class FrameLogin extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameLogin.class.getName());

    /** Creates new form FrameLogin */
    public FrameLogin() {
        initComponents();
        
        //memanggil method style saat dijalankan
        borderLengkung(containerLogin);
        borderLengkung(usrContainer);
        borderLengkung(passContainer);
        borderLengkung(roleContainer);
        buttonLengkung(btnLogin);
        
        
        
        
        
        
        
        
    }
    
    
    
    //membuat method style border lengkung pada button dan panel menggunakan flatline border dari flatlaf
    void borderLengkung(JPanel panel) {
        panel.setBorder(new FlatLineBorder(
                new Insets(0, 0, 0, 0),
                Color.decode("#E7BDBB"),
                1f,
                10
        ));
    }
    
    void buttonLengkung(JButton tombol) {
        tombol.putClientProperty("FlatLaf.style",
                "borderWidth:2; "
                + "arc:15; "
                + "borderColor:#000000; "
                + "focusedBorderColor:#000000; "
                + "hoverBorderColor:#000000"
        );

    }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new javax.swing.JPanel();
        rightContainer = new javax.swing.JPanel();
        containerLogin = new javax.swing.JPanel();
        jJpanelll = new javax.swing.JPanel();
        usrContainer = new javax.swing.JPanel();
        tUsername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Jpanell = new javax.swing.JPanel();
        lblPassword = new javax.swing.JLabel();
        passContainer = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tPassword = new javax.swing.JPasswordField();
        jToggleButton3 = new javax.swing.JToggleButton();
        Jpanelll = new javax.swing.JPanel();
        lblMasukSebagai = new javax.swing.JLabel();
        roleContainer = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cRole = new javax.swing.JComboBox<>();
        lblUsernameLogin = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        txtCopyright = new javax.swing.JLabel();
        leftContainer = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblToko = new javax.swing.JLabel();
        tDetail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));

        mainPanel.setBackground(new java.awt.Color(252, 249, 255));
        mainPanel.setMinimumSize(new java.awt.Dimension(1280, 720));
        mainPanel.setPreferredSize(new java.awt.Dimension(1280, 720));
        mainPanel.setLayout(new java.awt.GridBagLayout());

        rightContainer.setBackground(new java.awt.Color(252, 249, 255));
        rightContainer.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 22));

        containerLogin.setBackground(new java.awt.Color(255, 255, 255));
        containerLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 189, 187)));

        jJpanelll.setBackground(new java.awt.Color(255, 255, 255));
        jJpanelll.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usrContainer.setBackground(new java.awt.Color(255, 255, 255));
        usrContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 189, 187)));

        tUsername.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 16)); // NOI18N
        tUsername.setText("Masukkan Username");
        tUsername.setBorder(null);
        tUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tUsernameFocusLost(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new FlatSVGIcon("posseblakratu/icon/IconUsr.svg")
        );

        javax.swing.GroupLayout usrContainerLayout = new javax.swing.GroupLayout(usrContainer);
        usrContainer.setLayout(usrContainerLayout);
        usrContainerLayout.setHorizontalGroup(
            usrContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usrContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addContainerGap())
        );
        usrContainerLayout.setVerticalGroup(
            usrContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usrContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(usrContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jJpanelll.add(usrContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, -1));

        Jpanell.setBackground(new java.awt.Color(255, 255, 255));
        Jpanell.setAlignmentX(1.0F);
        Jpanell.setAlignmentY(1.0F);

        lblPassword.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        lblPassword.setText("Password");

        passContainer.setBackground(new java.awt.Color(255, 255, 255));
        passContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 189, 187)));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new FlatSVGIcon("posseblakratu/icon/IconPass.svg")
        );

        tPassword.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 16)); // NOI18N
        tPassword.setText("Masukkan password");
        tPassword.setBorder(null);

        jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posseblakratu/icon/IconMata.png"))); // NOI18N
        jToggleButton3.setBorder(null);
        jToggleButton3.setContentAreaFilled(false);
        jToggleButton3.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/posseblakratu/icon/IconMata.png"))); // NOI18N
        jToggleButton3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/posseblakratu/icon/DisIconMata2.png"))); // NOI18N
        jToggleButton3.addActionListener(this::jToggleButton3ActionPerformed);

        javax.swing.GroupLayout passContainerLayout = new javax.swing.GroupLayout(passContainer);
        passContainer.setLayout(passContainerLayout);
        passContainerLayout.setHorizontalGroup(
            passContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        passContainerLayout.setVerticalGroup(
            passContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(passContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(tPassword))
                .addContainerGap())
            .addComponent(jToggleButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout JpanellLayout = new javax.swing.GroupLayout(Jpanell);
        Jpanell.setLayout(JpanellLayout);
        JpanellLayout.setHorizontalGroup(
            JpanellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(passContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JpanellLayout.setVerticalGroup(
            JpanellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanellLayout.createSequentialGroup()
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        Jpanelll.setBackground(new java.awt.Color(255, 255, 255));
        Jpanelll.setAlignmentX(1.0F);
        Jpanelll.setAlignmentY(1.0F);

        lblMasukSebagai.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        lblMasukSebagai.setText("Masuk Sebagai");

        roleContainer.setBackground(new java.awt.Color(255, 255, 255));
        roleContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 189, 187)));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new FlatSVGIcon("posseblakratu/icon/IconRole.svg")
        );

        cRole.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 16)); // NOI18N
        cRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kasir", "Owner" }));
        cRole.setBorder(null);

        javax.swing.GroupLayout roleContainerLayout = new javax.swing.GroupLayout(roleContainer);
        roleContainer.setLayout(roleContainerLayout);
        roleContainerLayout.setHorizontalGroup(
            roleContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roleContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cRole, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        roleContainerLayout.setVerticalGroup(
            roleContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roleContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roleContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(cRole))
                .addContainerGap())
        );

        javax.swing.GroupLayout JpanelllLayout = new javax.swing.GroupLayout(Jpanelll);
        Jpanelll.setLayout(JpanelllLayout);
        JpanelllLayout.setHorizontalGroup(
            JpanelllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMasukSebagai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(roleContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JpanelllLayout.setVerticalGroup(
            JpanelllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelllLayout.createSequentialGroup()
                .addComponent(lblMasukSebagai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roleContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        lblUsernameLogin.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        lblUsernameLogin.setText("Username");

        btnLogin.setBackground(new java.awt.Color(214, 4, 39));
        btnLogin.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 16)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setIcon(new FlatSVGIcon("posseblakratu/icon/IconLogin.svg")
        );
        btnLogin.setText("Login");
        btnLogin.setBorderPainted(false);
        btnLogin.setFocusPainted(false);
        btnLogin.setFocusable(false);
        btnLogin.addActionListener(this::btnLoginActionPerformed);

        javax.swing.GroupLayout containerLoginLayout = new javax.swing.GroupLayout(containerLogin);
        containerLogin.setLayout(containerLoginLayout);
        containerLoginLayout.setHorizontalGroup(
            containerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLoginLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(containerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jJpanelll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Jpanell, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Jpanelll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUsernameLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        containerLoginLayout.setVerticalGroup(
            containerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLoginLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblUsernameLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jJpanelll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(Jpanell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(Jpanelll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        rightContainer.add(containerLogin);

        txtCopyright.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        txtCopyright.setForeground(new java.awt.Color(92, 62, 60));
        txtCopyright.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCopyright.setText("© 2026 Ratu Seblak POS System. All rights reserved.");
        txtCopyright.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rightContainer.add(txtCopyright);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = -298;
        gridBagConstraints.ipady = 61;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(110, 70, 130, 200);
        mainPanel.add(rightContainer, gridBagConstraints);

        leftContainer.setBackground(new java.awt.Color(252, 249, 255));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posseblakratu/icon/logo.png"))); // NOI18N
        lblLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        leftContainer.add(lblLogo);

        lblToko.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 40)); // NOI18N
        lblToko.setForeground(new java.awt.Color(214, 4, 39));
        lblToko.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblToko.setText("RATU SEBLAK");
        leftContainer.add(lblToko);

        tDetail.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        tDetail.setForeground(new java.awt.Color(92, 62, 60));
        tDetail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tDetail.setText("Sistem Point of Sale");
        leftContainer.add(tDetail);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -254;
        gridBagConstraints.ipady = 81;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(220, 190, 100, 0);
        mainPanel.add(leftContainer, gridBagConstraints);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        
        new FrameUtama().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void tUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tUsernameFocusGained
        // TODO add your handling code here:
        String ID = tUsername.getText();
        if(ID.equals("Masukkan Username")){
            tUsername.setText("");
        }
    }//GEN-LAST:event_tUsernameFocusGained

    private void tUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tUsernameFocusLost
        // TODO add your handling code here:
        String ID = tUsername.getText();
        if(ID.equals("")||ID.equals("Masukkan Username")){
            tUsername.setText("Masukkan Username");
        }
    }//GEN-LAST:event_tUsernameFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException unsupportedLookAndFeelException) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jpanell;
    private javax.swing.JPanel Jpanelll;
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<String> cRole;
    private javax.swing.JPanel containerLogin;
    private javax.swing.JPanel jJpanelll;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMasukSebagai;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblToko;
    private javax.swing.JLabel lblUsernameLogin;
    private javax.swing.JPanel leftContainer;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel passContainer;
    private javax.swing.JPanel rightContainer;
    private javax.swing.JPanel roleContainer;
    private javax.swing.JLabel tDetail;
    private javax.swing.JPasswordField tPassword;
    private javax.swing.JTextField tUsername;
    private javax.swing.JLabel txtCopyright;
    private javax.swing.JPanel usrContainer;
    // End of variables declaration//GEN-END:variables

}
