/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package posseblakratu.view;


import com.formdev.flatlaf.ui.FlatLineBorder;
import java.awt.Color;
import java.awt.Insets;
import javax.swing.JPanel;
import posseblakratu.component.DesainUI;



/**
 *
 * @author Al
 */
public final class PanelProduk extends javax.swing.JPanel {

    /**
     * Creates new form PanelProduk
     */
    public PanelProduk() {
        initComponents();
        
        panelLengkung(jPanel17);
        panelLengkung(jPanel18);
        panelLengkung(jPanel20);
        panelLengkung(jPanel19);


        

        
        filterSemuaP.setSelected(true);
        filterSemuaP.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(173,0,28)));
        filterSeblakP.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 3, 0));
        filterToppingP.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 3, 0));
        filterMinumanP.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 3, 0));
        
    }
    
    
    void panelLengkung(JPanel p) {
        
        p.setBorder(new FlatLineBorder(
                new Insets(3, 3, 3, 3),
                Color.decode("#E7BDBB"),
                1f,
                10));
        
        
        jPanel1.setBorder(new FlatLineBorder(
                new Insets(5, 5, 5, 5),
                Color.decode("#E7BDBB"),
                1f,
                10));
        
        jPanel3.setBorder(new FlatLineBorder(
                new Insets(5, 5, 5, 5),
                Color.decode("#E7BDBB"),
                1f,
                10));
    }
    

    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTambahProduk = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnSimpanProduk = new javax.swing.JButton();
        btnBatalProduk = new javax.swing.JButton();
        btnHapusProduk = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        lblNamaProduk = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        tNamaProduk = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        lblNamaProduk1 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        tDeskProduk = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        lblNamaProduk2 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        cKategoriProduk = new javax.swing.JComboBox<>();
        jPanel15 = new javax.swing.JPanel();
        lblNamaProduk3 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        tHargaProduk = new javax.swing.JTextField();
        lblRupiahProduk = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        lblStatusProduk = new javax.swing.JLabel();
        btnStatusProduk = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabell = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        btnTambahProduk = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        filterSemuaP = new javax.swing.JToggleButton();
        filterSeblakP = new javax.swing.JToggleButton();
        filterToppingP = new javax.swing.JToggleButton();
        filterMinumanP = new javax.swing.JToggleButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDaftarProduk = new posseblakratu.component.TableCustom();

        setBackground(new java.awt.Color(252, 249, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        setMinimumSize(new java.awt.Dimension(1075, 639));
        setLayout(new java.awt.BorderLayout(15, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 189, 187)));
        jPanel1.setPreferredSize(new java.awt.Dimension(347, 611));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(231, 189, 187)));
        jPanel2.setMinimumSize(new java.awt.Dimension(335, 63));
        jPanel2.setPreferredSize(new java.awt.Dimension(335, 63));

        lblTambahProduk.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 18)); // NOI18N
        lblTambahProduk.setText("Tambah  Produk");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTambahProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTambahProduk, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(21, 21, 20, 21));
        jPanel4.setMinimumSize(new java.awt.Dimension(345, 130));
        jPanel4.setPreferredSize(new java.awt.Dimension(345, 130));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        btnSimpanProduk.setBackground(new java.awt.Color(214, 4, 39));
        btnSimpanProduk.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 16)); // NOI18N
        btnSimpanProduk.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpanProduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posseblakratu/icon/IconSimpan.png"))); // NOI18N
        btnSimpanProduk.setText("Simpan Perubahan");
        btnSimpanProduk.setBorderPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 111;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 21, 0, 21);
        jPanel4.add(btnSimpanProduk, gridBagConstraints);

        btnBatalProduk.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 16)); // NOI18N
        btnBatalProduk.setText("Batal");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 73;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 21, 20, 0);
        jPanel4.add(btnBatalProduk, gridBagConstraints);

        btnHapusProduk.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 16)); // NOI18N
        btnHapusProduk.setForeground(new java.awt.Color(214, 4, 39));
        btnHapusProduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posseblakratu/icon/Vector.png"))); // NOI18N
        btnHapusProduk.setText("Hapus");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 51;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 20, 0);
        jPanel4.add(btnHapusProduk, gridBagConstraints);

        jPanel1.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(231, 189, 187)));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createEmptyBorder(18, 18, 0, 18));
        jPanel11.setMaximumSize(new java.awt.Dimension(32767, 350));
        jPanel11.setPreferredSize(new java.awt.Dimension(345, 340));
        jPanel11.setLayout(new java.awt.GridLayout(5, 1, 0, 10));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new java.awt.BorderLayout());

        lblNamaProduk.setBackground(new java.awt.Color(255, 255, 255));
        lblNamaProduk.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        lblNamaProduk.setText("Nama Produk");
        lblNamaProduk.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 4, 0));
        jPanel12.add(lblNamaProduk, java.awt.BorderLayout.PAGE_START);

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 189, 187)));
        jPanel17.setLayout(new java.awt.GridBagLayout());

        tNamaProduk.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 16)); // NOI18N
        tNamaProduk.setForeground(new java.awt.Color(92, 62, 60));
        tNamaProduk.setText("Contoh: Es Jeruk");
        tNamaProduk.setBorder(null);
        tNamaProduk.setMargin(new java.awt.Insets(10, 10, 10, 6));
        tNamaProduk.setPreferredSize(new java.awt.Dimension(126, 19));
        tNamaProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tNamaProdukMouseClicked(evt);
            }
        });
        tNamaProduk.addActionListener(this::tNamaProdukActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 278;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.insets = new java.awt.Insets(1, 18, 1, 12);
        jPanel17.add(tNamaProduk, gridBagConstraints);

        jPanel12.add(jPanel17, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel12);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new java.awt.BorderLayout());

        lblNamaProduk1.setBackground(new java.awt.Color(255, 255, 255));
        lblNamaProduk1.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        lblNamaProduk1.setText("Deskripsi");
        lblNamaProduk1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 4, 0));
        jPanel13.add(lblNamaProduk1, java.awt.BorderLayout.PAGE_START);

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 189, 187)));
        jPanel18.setLayout(new java.awt.GridBagLayout());

        tDeskProduk.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 16)); // NOI18N
        tDeskProduk.setForeground(new java.awt.Color(92, 62, 60));
        tDeskProduk.setText("Opsional");
        tDeskProduk.setBorder(null);
        tDeskProduk.setMargin(new java.awt.Insets(10, 10, 10, 6));
        tDeskProduk.setPreferredSize(new java.awt.Dimension(126, 19));
        tDeskProduk.addActionListener(this::tDeskProdukActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 278;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.insets = new java.awt.Insets(1, 18, 1, 12);
        jPanel18.add(tDeskProduk, gridBagConstraints);

        jPanel13.add(jPanel18, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel13);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(new java.awt.BorderLayout());

        lblNamaProduk2.setBackground(new java.awt.Color(255, 255, 255));
        lblNamaProduk2.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        lblNamaProduk2.setText("Kategori");
        lblNamaProduk2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 4, 0));
        jPanel14.add(lblNamaProduk2, java.awt.BorderLayout.PAGE_START);

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 189, 187)));
        jPanel20.setLayout(new java.awt.BorderLayout());

        cKategoriProduk.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 16)); // NOI18N
        cKategoriProduk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seblak", "Topping", "Minuman" }));
        cKategoriProduk.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 12, 1, 12));
        jPanel20.add(cKategoriProduk, java.awt.BorderLayout.CENTER);

        jPanel14.add(jPanel20, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel14);

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setLayout(new java.awt.BorderLayout());

        lblNamaProduk3.setBackground(new java.awt.Color(255, 255, 255));
        lblNamaProduk3.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        lblNamaProduk3.setText("Harga Jual");
        lblNamaProduk3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 4, 0));
        jPanel15.add(lblNamaProduk3, java.awt.BorderLayout.PAGE_START);

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 189, 187)));
        jPanel19.setLayout(new java.awt.BorderLayout());

        tHargaProduk.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 18)); // NOI18N
        tHargaProduk.setForeground(new java.awt.Color(215, 4, 39));
        tHargaProduk.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tHargaProduk.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 15));
        tHargaProduk.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tHargaProduk.setMargin(new java.awt.Insets(10, 20, 10, 6));
        tHargaProduk.setOpaque(true);
        tHargaProduk.addActionListener(this::tHargaProdukActionPerformed);
        jPanel19.add(tHargaProduk, java.awt.BorderLayout.CENTER);

        lblRupiahProduk.setBackground(new java.awt.Color(255, 255, 255));
        lblRupiahProduk.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 18)); // NOI18N
        lblRupiahProduk.setForeground(new java.awt.Color(215, 4, 39));
        lblRupiahProduk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRupiahProduk.setText("Rp");
        lblRupiahProduk.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(231, 189, 187)), javax.swing.BorderFactory.createEmptyBorder(1, 12, 1, 12)));
        lblRupiahProduk.setOpaque(true);
        jPanel19.add(lblRupiahProduk, java.awt.BorderLayout.LINE_START);

        jPanel15.add(jPanel19, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel15);

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));

        lblStatusProduk.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        lblStatusProduk.setText(" Status Ketersediaan");

        btnStatusProduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posseblakratu/icon/Property 1=Variant2.png"))); // NOI18N
        btnStatusProduk.setBorder(null);
        btnStatusProduk.setContentAreaFilled(false);
        btnStatusProduk.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/posseblakratu/icon/Property 1=Variant2.png"))); // NOI18N
        btnStatusProduk.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/posseblakratu/icon/icon on.png"))); // NOI18N

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 309, Short.MAX_VALUE)
            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel16Layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(lblStatusProduk)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel16Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnStatusProduk)
                    .addGap(0, 0, 0)))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel16Layout.createSequentialGroup()
                    .addGap(0, 25, Short.MAX_VALUE)
                    .addComponent(lblStatusProduk)
                    .addGap(0, 25, Short.MAX_VALUE)))
            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel16Layout.createSequentialGroup()
                    .addGap(0, 18, Short.MAX_VALUE)
                    .addComponent(btnStatusProduk)
                    .addGap(0, 19, Short.MAX_VALUE)))
        );

        jPanel11.add(jPanel16);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.LINE_END);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 189, 187)));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(231, 189, 187)));
        jPanel5.setPreferredSize(new java.awt.Dimension(681, 112));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(681, 63));

        jLabell.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 24)); // NOI18N
        jLabell.setForeground(new java.awt.Color(24, 26, 46));
        jLabell.setText("Daftar Produk");
        jLabell.setMaximumSize(new java.awt.Dimension(198, 31));
        jLabell.setMinimumSize(new java.awt.Dimension(198, 31));
        jLabell.setName(""); // NOI18N
        jLabell.setPreferredSize(new java.awt.Dimension(198, 63));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createEmptyBorder(16, 0, 16, 0));
        jPanel10.setPreferredSize(new java.awt.Dimension(150, 60));
        jPanel10.setLayout(new java.awt.BorderLayout());

        btnTambahProduk.setBackground(new java.awt.Color(214, 4, 39));
        btnTambahProduk.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 16)); // NOI18N
        btnTambahProduk.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahProduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posseblakratu/icon/IconPlus.png"))); // NOI18N
        btnTambahProduk.setText("Tambah Baru");
        btnTambahProduk.setBorderPainted(false);
        jPanel10.add(btnTambahProduk, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabell, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabell, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel8, java.awt.BorderLayout.PAGE_START);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        buttonGroup1.add(filterSemuaP);
        filterSemuaP.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        filterSemuaP.setForeground(new java.awt.Color(92, 62, 60));
        filterSemuaP.setText("Semua");
        filterSemuaP.setAlignmentY(0.0F);
        filterSemuaP.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        filterSemuaP.setContentAreaFilled(false);
        filterSemuaP.setFocusable(false);
        filterSemuaP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        filterSemuaP.setIconTextGap(0);
        filterSemuaP.setMargin(new java.awt.Insets(0, 0, 0, 0));
        filterSemuaP.addItemListener(this::filterSemuaPItemStateChanged);

        buttonGroup1.add(filterSeblakP);
        filterSeblakP.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        filterSeblakP.setForeground(new java.awt.Color(92, 62, 60));
        filterSeblakP.setText("Seblak");
        filterSeblakP.setAlignmentY(0.0F);
        filterSeblakP.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        filterSeblakP.setContentAreaFilled(false);
        filterSeblakP.setFocusable(false);
        filterSeblakP.setIconTextGap(0);
        filterSeblakP.setMargin(new java.awt.Insets(1, 1, 20, 1));
        filterSeblakP.addItemListener(this::filterSeblakPItemStateChanged);

        buttonGroup1.add(filterToppingP);
        filterToppingP.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        filterToppingP.setForeground(new java.awt.Color(92, 62, 60));
        filterToppingP.setText("Topping");
        filterToppingP.setAlignmentY(0.0F);
        filterToppingP.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        filterToppingP.setContentAreaFilled(false);
        filterToppingP.setFocusable(false);
        filterToppingP.setIconTextGap(0);
        filterToppingP.setMargin(new java.awt.Insets(1, 1, 20, 1));
        filterToppingP.setMaximumSize(new java.awt.Dimension(62, 48));
        filterToppingP.setMinimumSize(new java.awt.Dimension(62, 48));
        filterToppingP.setPreferredSize(new java.awt.Dimension(62, 48));
        filterToppingP.addItemListener(this::filterToppingPItemStateChanged);

        buttonGroup1.add(filterMinumanP);
        filterMinumanP.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        filterMinumanP.setForeground(new java.awt.Color(92, 62, 60));
        filterMinumanP.setText("Minuman");
        filterMinumanP.setAlignmentY(0.0F);
        filterMinumanP.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        filterMinumanP.setContentAreaFilled(false);
        filterMinumanP.setFocusable(false);
        filterMinumanP.setIconTextGap(0);
        filterMinumanP.setMargin(new java.awt.Insets(1, 1, 20, 1));
        filterMinumanP.setMaximumSize(new java.awt.Dimension(62, 48));
        filterMinumanP.setMinimumSize(new java.awt.Dimension(62, 48));
        filterMinumanP.setPreferredSize(new java.awt.Dimension(62, 48));
        filterMinumanP.addItemListener(this::filterMinumanPItemStateChanged);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(filterSemuaP)
                .addGap(12, 12, 12)
                .addComponent(filterSeblakP)
                .addGap(12, 12, 12)
                .addComponent(filterToppingP, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(filterMinumanP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(408, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filterToppingP, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterMinumanP, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(filterSeblakP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(filterSemuaP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel9, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.BorderLayout());

        tblDaftarProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"M001", "Es Jeruk", "Minuman", "Rp 4.000", "Tersedia"},
                {"M002", "Es Teh", "Minuman", "Rp 3.000", "Tersedia"},
                {"S001", "Seblak Original", "Seblak", "Rp 9.000", "Tersedia"}
            },
            new String [] {
                "ID", "Nama Produk", "Kategori", "Harga Jual", "Status"
            }
        ));
        tblDaftarProduk.setCellPaddingLeft(25);
        tblDaftarProduk.setCenterColumns("2,3,4");
        tblDaftarProduk.setColumnWidths("70,200,110,110,110");
        tblDaftarProduk.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        tblDaftarProduk.setGridColor(new java.awt.Color(231, 189, 187));
        tblDaftarProduk.setHeaderBorderColor(new java.awt.Color(231, 189, 187));
        tblDaftarProduk.setHeaderPaddingLeft(25);
        tblDaftarProduk.setOuterBorderThickness(0);
        tblDaftarProduk.setRowBorderColor(new java.awt.Color(231, 189, 187));
        jScrollPane2.setViewportView(tblDaftarProduk);

        jPanel6.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel6, java.awt.BorderLayout.CENTER);

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void filterSemuaPItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filterSemuaPItemStateChanged
        // TODO add your handling code here:
        if (filterSemuaP.isSelected()) {
            filterSemuaP.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(173,0,28)));
        } else {
            filterSemuaP.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 3, 0));
        }
    }//GEN-LAST:event_filterSemuaPItemStateChanged

    private void filterSeblakPItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filterSeblakPItemStateChanged
        // TODO add your handling code here:
        if (filterSeblakP.isSelected()) {
            filterSeblakP.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(173,0,28)));
        } else {
            filterSeblakP.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 3, 0));
        }
    }//GEN-LAST:event_filterSeblakPItemStateChanged

    private void filterToppingPItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filterToppingPItemStateChanged
        // TODO add your handling code here:
        if (filterToppingP.isSelected()) {
            filterToppingP.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(173,0,28)));
        } else {
            filterToppingP.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 3, 0));
        }
    }//GEN-LAST:event_filterToppingPItemStateChanged

    private void filterMinumanPItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filterMinumanPItemStateChanged
        // TODO add your handling code here:
        if (filterMinumanP.isSelected()) {
            filterMinumanP.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(173,0,28)));
        } else {
            filterMinumanP.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 3, 0));
        }
    }//GEN-LAST:event_filterMinumanPItemStateChanged

    private void tHargaProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tHargaProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tHargaProdukActionPerformed

    private void tDeskProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDeskProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tDeskProdukActionPerformed

    private void tNamaProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNamaProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNamaProdukActionPerformed

    private void tNamaProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tNamaProdukMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tNamaProdukMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalProduk;
    private javax.swing.JButton btnHapusProduk;
    private javax.swing.JButton btnSimpanProduk;
    private javax.swing.JToggleButton btnStatusProduk;
    private javax.swing.JButton btnTambahProduk;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cKategoriProduk;
    private javax.swing.JToggleButton filterMinumanP;
    private javax.swing.JToggleButton filterSeblakP;
    private javax.swing.JToggleButton filterSemuaP;
    private javax.swing.JToggleButton filterToppingP;
    private javax.swing.JLabel jLabell;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNamaProduk;
    private javax.swing.JLabel lblNamaProduk1;
    private javax.swing.JLabel lblNamaProduk2;
    private javax.swing.JLabel lblNamaProduk3;
    private javax.swing.JLabel lblRupiahProduk;
    private javax.swing.JLabel lblStatusProduk;
    private javax.swing.JLabel lblTambahProduk;
    private javax.swing.JTextField tDeskProduk;
    private javax.swing.JTextField tHargaProduk;
    private javax.swing.JTextField tNamaProduk;
    private posseblakratu.component.TableCustom tblDaftarProduk;
    // End of variables declaration//GEN-END:variables
}
