/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package posseblakratu.component;

import com.formdev.flatlaf.ui.FlatLineBorder;
import java.awt.Color;
import java.awt.Insets;
import java.awt.event.MouseListener;

/**
 *
 * @author Al
 */
public class cardMenu extends javax.swing.JPanel {

    private boolean selected = false;  //membuat variable status card menu false

    //deklarasi variable untuk menyimpan data menu
    private String idProduk;
    private String namaMenu;
    private double hargaMenu;
    private String deskripsiMenu;
    private String kategoriMenu;
   
    

    /**
     * Creates new form cardMenu
     */
    public cardMenu() {
        initComponents();

        updateStyle();  //memanggil style card menu

    }

    //membuat styling selected dan !selected
    private void updateStyle() {
        if (selected) {
            setBorder(new FlatLineBorder(
                    new Insets(0, 0, 0, 0),
                    Color.decode("#EA580C"),
                    2.5f,
                    10));
        } else {
            setBorder(new FlatLineBorder(
                    new Insets(0, 0, 0, 0),
                    new Color(231, 189, 187),
                    1,
                    10));
        }
        repaint();
    }

    public void setSelected(boolean selected) {     //membuat setter selected
        this.selected = selected; //mengubah status card
        updateStyle();  //memperbarui tampilan setelah status berubah
    }

    public boolean isSelected() {  //membuat getter selected untuk mengembalikan nilai selected
        return selected;
    }

    

    //Membuat method click listener agar saat semua bagian card bisa di klik
    public void addClickListener(MouseListener listener) {
        addMouseListener(listener);
        jPanel2.addMouseListener(listener);
        lblMenu.addMouseListener(listener);
        lblHarga.addMouseListener(listener);
        lblDesk.addMouseListener(listener);
    }

    //method untuk mengisi data pada card menu
    public void setData(String idProduk, String namaMenu, double hargaMenu, String kategoriMenu, String deskripsiMenu) { //pastikan urutan penamaan variable di ingat

        //menyimpan data produk
        this.idProduk = idProduk;
        this.namaMenu = namaMenu;
        this.hargaMenu = hargaMenu;
        this.kategoriMenu = kategoriMenu;
        this.deskripsiMenu = deskripsiMenu;

        //menampilkan nama produk
        lblMenu.setText(namaMenu);

        //menampilkan harga produk
        lblHarga.setText("Rp. " + (int) hargaMenu);

        //memeriksa apakah deskripsi kosong
        if (deskripsiMenu == null || deskripsiMenu.trim().isEmpty()) {

            //jika deskripsi kosong, tampilkan tanda "-"
            lblDesk.setText("-");

        } else {

            //jika deskripsi ada, tampilkan deskripsi produk
            lblDesk.setText(deskripsiMenu);

        }

    }

    //membuat getter agar data dapat di panggil dari class manapun
    public String getIdProduk() {
        return idProduk;
    }

    public String getNama() {
        return namaMenu;
    }

    public double getHarga() {
        return hargaMenu;
    }

    public String getKategori() {
        return kategoriMenu;
    }

    public String getDeskripsi() {
        return deskripsiMenu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblMenu = new javax.swing.JLabel();
        lblHarga = new javax.swing.JLabel();
        lblDesk = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setFocusable(false);

        lblMenu.setBackground(new java.awt.Color(153, 255, 153));
        lblMenu.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        lblMenu.setForeground(new java.awt.Color(24, 26, 46));
        lblMenu.setText("Seblak Original");

        lblHarga.setBackground(new java.awt.Color(153, 255, 153));
        lblHarga.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        lblHarga.setForeground(new java.awt.Color(214, 4, 39));
        lblHarga.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHarga.setText("Rp. 9000");

        lblDesk.setEditable(false);
        lblDesk.setBackground(new java.awt.Color(255, 255, 255));
        lblDesk.setColumns(100);
        lblDesk.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 12)); // NOI18N
        lblDesk.setLineWrap(true);
        lblDesk.setRows(2);
        lblDesk.setTabSize(0);
        lblDesk.setBorder(null);
        lblDesk.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        lblDesk.setEnabled(false);
        lblDesk.setFocusable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDesk, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(lblHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMenu)
                    .addComponent(lblHarga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDesk, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextArea lblDesk;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblMenu;
    // End of variables declaration//GEN-END:variables
}
