/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package posseblakratu.component;

import posseblakratu.config.FormatUang;
public class cardTopping extends javax.swing.JPanel {

    //deklarasi varible untuk menyimpan data topping
    private String idProduk;
    private String namaTopping;
    private double hargaTopping;

    /**
     * Creates new form cardTopping
     */
    public cardTopping() {
        initComponents();
    }

    //method untuk mengisi data pada card topping
    public void setData(String idProduk, String namaTopping, double hargaTopping) {

        //menyimpan data topping
        this.idProduk = idProduk;
        this.namaTopping = namaTopping;
        this.hargaTopping = hargaTopping;

        //menampilkan nama produk
        lblTopping.setText(namaTopping);

        //menampilkan harga produk
        lblHargaTopping.setText(FormatUang.format(hargaTopping));

    }

    //mengembalikan id produk topping
    public String getIdProduk() {
        return idProduk;
    }

    //mengembalikan nama topping
    public String getNama() {
        return namaTopping;
    }

    //mengembalikan harga topping
    public double getHarga() {
        return hargaTopping;
    }

    //getter qty stepper untuk membaca value dari qtystepper
    public int getQty() {
        return qtyTopping.getValue();
    }

    //method untuk mengembalikan qty topping ke nilai awal
    public void resetQty() {
        //mengatur qty menjadi nol
        qtyTopping.setValue(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTopping = new javax.swing.JLabel();
        lblHargaTopping = new javax.swing.JLabel();
        qtyTopping = new qtystepper.qtyStepper();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(231, 189, 187)));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblTopping.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        lblTopping.setText("Mie");

        lblHargaTopping.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 11)); // NOI18N
        lblHargaTopping.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHargaTopping.setText("+ 1.000");

        qtyTopping.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 14)); // NOI18N

        javax.swing.GroupLayout qtyToppingLayout = new javax.swing.GroupLayout(qtyTopping);
        qtyTopping.setLayout(qtyToppingLayout);
        qtyToppingLayout.setHorizontalGroup(
            qtyToppingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 82, Short.MAX_VALUE)
        );
        qtyToppingLayout.setVerticalGroup(
            qtyToppingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(lblTopping, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHargaTopping, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(qtyTopping, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTopping, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(lblHargaTopping, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(qtyTopping, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHargaTopping;
    private javax.swing.JLabel lblTopping;
    private qtystepper.qtyStepper qtyTopping;
    // End of variables declaration//GEN-END:variables
}
