/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package seblakratupos.view;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.Color;


/**
 *
 * @author Al
 */
public class LoginFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginFrame.class.getName());

    /**
     * Creates new form frameLogin
     */
    public LoginFrame() {
    initComponents();
    
    txtUsername.setText("Masukkan username");
    txtUsername.setForeground(Color.GRAY);

    txtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusGained(java.awt.event.FocusEvent evt) {
            if (txtUsername.getText().equals("Masukkan username")) {
                txtUsername.setText("");
                txtUsername.setForeground(Color.BLACK);
            }
        }

        @Override
        public void focusLost(java.awt.event.FocusEvent evt) {
            if (txtUsername.getText().isEmpty()) {
                txtUsername.setText("Masukkan username");
                txtUsername.setForeground(Color.GRAY);
            }
        }
    });
    
    
    final char defaultEchoChar = txtPassword.getEchoChar();

    txtPassword.setText("Masukkan password");
    txtPassword.setForeground(Color.GRAY);

    // Biar tulisan placeholder tidak jadi bintang
    txtPassword.setEchoChar((char) 0);

    txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusGained(java.awt.event.FocusEvent evt) {
            String password = new String(txtPassword.getPassword());

            if (password.equals("Masukkan password")) {
                txtPassword.setText("");
                txtPassword.setForeground(Color.BLACK);

                // Balikin jadi mode password, jadi nanti ketikan user jadi bintang
                txtPassword.setEchoChar(defaultEchoChar);
            }
        }

        @Override
        public void focusLost(java.awt.event.FocusEvent evt) {
            String password = new String(txtPassword.getPassword());

            if (password.isEmpty()) {
                txtPassword.setText("Masukkan password");
                txtPassword.setForeground(Color.GRAY);

                // Matikan sensor lagi biar placeholder terbaca normal
                txtPassword.setEchoChar((char) 0);
            }
        }
    });

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new javax.swing.JPanel();
        rightContainer = new javax.swing.JPanel();
        loginContainer = new seblakratupos.view.component.PanelCustom();
        usrContainer = new javax.swing.JPanel();
        lblUsernameLogin = new javax.swing.JLabel();
        panelCustom1 = new seblakratupos.view.component.PanelCustom();
        txtUsername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        passContainer = new javax.swing.JPanel();
        lblPassword = new javax.swing.JLabel();
        panelCustom2 = new seblakratupos.view.component.PanelCustom();
        jLabel6 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new seblakratupos.view.component.ButtonCustom();
        passContainer1 = new javax.swing.JPanel();
        lblMasukSebagai = new javax.swing.JLabel();
        panelCustom3 = new seblakratupos.view.component.PanelCustom();
        jLabel8 = new javax.swing.JLabel();
        cMasukSebagai = new seblakratupos.view.component.ComboBoxCustom();
        txtCopyright = new javax.swing.JLabel();
        leftContainer = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        tNamaToko = new javax.swing.JLabel();
        tDetail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");

        mainPanel.setBackground(new java.awt.Color(252, 249, 255));
        mainPanel.setPreferredSize(new java.awt.Dimension(1280, 720));
        mainPanel.setLayout(new java.awt.GridBagLayout());

        rightContainer.setBackground(new java.awt.Color(252, 249, 255));
        rightContainer.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 22));

        loginContainer.setBackground(new java.awt.Color(255, 255, 255));
        loginContainer.setBorderColor(new java.awt.Color(231, 189, 187));
        loginContainer.setBorderThickness(1);
        loginContainer.setPreferredSize(new java.awt.Dimension(448, 398));
        loginContainer.setRoundBottomLeft(8);
        loginContainer.setRoundBottomRight(8);
        loginContainer.setRoundTopLeft(8);
        loginContainer.setRoundTopRight(8);

        usrContainer.setBackground(new java.awt.Color(255, 255, 255));
        usrContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsernameLogin.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        lblUsernameLogin.setText("Username");
        usrContainer.add(lblUsernameLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, -1));

        panelCustom1.setBackground(new java.awt.Color(255, 255, 255));
        panelCustom1.setBorderColor(new java.awt.Color(231, 189, 187));
        panelCustom1.setBorderThickness(1);
        panelCustom1.setRoundBottomLeft(3);
        panelCustom1.setRoundBottomRight(3);
        panelCustom1.setRoundTopLeft(3);
        panelCustom1.setRoundTopRight(3);

        txtUsername.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 16)); // NOI18N
        txtUsername.setText("Masukkan Username");
        txtUsername.setBorder(null);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new FlatSVGIcon("seblakratupos/asset/icon/IconUsr.svg")
        );

        javax.swing.GroupLayout panelCustom1Layout = new javax.swing.GroupLayout(panelCustom1);
        panelCustom1.setLayout(panelCustom1Layout);
        panelCustom1Layout.setHorizontalGroup(
            panelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustom1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCustom1Layout.setVerticalGroup(
            panelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustom1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        usrContainer.add(panelCustom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 25, 400, -1));

        passContainer.setBackground(new java.awt.Color(255, 255, 255));
        passContainer.setAlignmentX(1.0F);
        passContainer.setAlignmentY(1.0F);

        lblPassword.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        lblPassword.setText("Password");

        panelCustom2.setBackground(new java.awt.Color(255, 255, 255));
        panelCustom2.setBorderColor(new java.awt.Color(231, 189, 187));
        panelCustom2.setBorderThickness(1);
        panelCustom2.setRoundBottomLeft(3);
        panelCustom2.setRoundBottomRight(3);
        panelCustom2.setRoundTopLeft(3);
        panelCustom2.setRoundTopRight(3);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new FlatSVGIcon("seblakratupos/asset/icon/IconPass.svg")
        );

        txtPassword.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 16)); // NOI18N
        txtPassword.setText("Masukkan password");
        txtPassword.setBorder(null);

        javax.swing.GroupLayout panelCustom2Layout = new javax.swing.GroupLayout(panelCustom2);
        panelCustom2.setLayout(panelCustom2Layout);
        panelCustom2Layout.setHorizontalGroup(
            panelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustom2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword)
                .addContainerGap())
        );
        panelCustom2Layout.setVerticalGroup(
            panelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustom2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(txtPassword))
                .addContainerGap())
        );

        javax.swing.GroupLayout passContainerLayout = new javax.swing.GroupLayout(passContainer);
        passContainer.setLayout(passContainerLayout);
        passContainerLayout.setHorizontalGroup(
            passContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCustom2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        passContainerLayout.setVerticalGroup(
            passContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passContainerLayout.createSequentialGroup()
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelCustom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnLogin.setBackground(new java.awt.Color(214, 4, 39));
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setIcon(new FlatSVGIcon("seblakratupos/asset/icon/IconLogin.svg")
        );
        btnLogin.setText("Login");
        btnLogin.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 16)); // NOI18N
        btnLogin.setHoverBackground(new java.awt.Color(214, 4, 39));
        btnLogin.setIconTextGap(8);
        btnLogin.setPressedBackground(new java.awt.Color(175, 3, 31));
        btnLogin.setRoundBottomLeft(3);
        btnLogin.setRoundBottomRight(3);
        btnLogin.setRoundTopLeft(3);
        btnLogin.setRoundTopRight(3);
        btnLogin.addActionListener(this::btnLoginActionPerformed);

        passContainer1.setBackground(new java.awt.Color(255, 255, 255));
        passContainer1.setAlignmentX(1.0F);
        passContainer1.setAlignmentY(1.0F);

        lblMasukSebagai.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        lblMasukSebagai.setText("Masuk Sebagai");

        panelCustom3.setBackground(new java.awt.Color(255, 255, 255));
        panelCustom3.setBorderColor(new java.awt.Color(231, 189, 187));
        panelCustom3.setBorderThickness(1);
        panelCustom3.setRoundBottomLeft(3);
        panelCustom3.setRoundBottomRight(3);
        panelCustom3.setRoundTopLeft(3);
        panelCustom3.setRoundTopRight(3);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new FlatSVGIcon("seblakratupos/asset/icon/IconRole.svg")
        );

        cMasukSebagai.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Owner", "Kasir" }));
        cMasukSebagai.setBorderThickness(0);
        cMasukSebagai.setDropdownTextLeftPadding(5);
        cMasukSebagai.setDropdownTextRightPadding(5);
        cMasukSebagai.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 16)); // NOI18N
        cMasukSebagai.setPopupBorderColor(new java.awt.Color(231, 189, 187));
        cMasukSebagai.setPopupBorderThickness(2);
        cMasukSebagai.setPopupRound(3);
        cMasukSebagai.setSelectedTextLeftPadding(0);
        cMasukSebagai.setSelectedTextOffsetX(-3);
        cMasukSebagai.setSelectedTextRightPadding(0);
        cMasukSebagai.setSelectionBackground(new java.awt.Color(252, 233, 232));
        cMasukSebagai.addActionListener(this::cMasukSebagaiActionPerformed);

        javax.swing.GroupLayout panelCustom3Layout = new javax.swing.GroupLayout(panelCustom3);
        panelCustom3.setLayout(panelCustom3Layout);
        panelCustom3Layout.setHorizontalGroup(
            panelCustom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustom3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cMasukSebagai, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelCustom3Layout.setVerticalGroup(
            panelCustom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustom3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCustom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cMasukSebagai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout passContainer1Layout = new javax.swing.GroupLayout(passContainer1);
        passContainer1.setLayout(passContainer1Layout);
        passContainer1Layout.setHorizontalGroup(
            passContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCustom3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblMasukSebagai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        passContainer1Layout.setVerticalGroup(
            passContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passContainer1Layout.createSequentialGroup()
                .addComponent(lblMasukSebagai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelCustom3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout loginContainerLayout = new javax.swing.GroupLayout(loginContainer);
        loginContainer.setLayout(loginContainerLayout);
        loginContainerLayout.setHorizontalGroup(
            loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginContainerLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usrContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passContainer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        loginContainerLayout.setVerticalGroup(
            loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginContainerLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(usrContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(passContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(passContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        rightContainer.add(loginContainer);

        txtCopyright.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        txtCopyright.setForeground(new java.awt.Color(92, 62, 60));
        txtCopyright.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCopyright.setText("© 2026 Ratu Seblak POS System. All rights reserved.");
        txtCopyright.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rightContainer.add(txtCopyright);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = -298;
        gridBagConstraints.ipady = 61;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(110, 70, 140, 200);
        mainPanel.add(rightContainer, gridBagConstraints);

        leftContainer.setBackground(new java.awt.Color(252, 249, 255));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seblakratupos/asset/img/logo.png"))); // NOI18N
        logo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        leftContainer.add(logo);

        tNamaToko.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 40)); // NOI18N
        tNamaToko.setForeground(new java.awt.Color(214, 4, 39));
        tNamaToko.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tNamaToko.setText("RATU SEBLAK");
        leftContainer.add(tNamaToko);

        tDetail.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        tDetail.setForeground(new java.awt.Color(92, 62, 60));
        tDetail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tDetail.setText("Sistem Point of Sale");
        leftContainer.add(tDetail);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -254;
        gridBagConstraints.ipady = 81;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(220, 190, 0, 0);
        mainPanel.add(leftContainer, gridBagConstraints);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        new MainFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void cMasukSebagaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cMasukSebagaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cMasukSebagaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private seblakratupos.view.component.ButtonCustom btnLogin;
    private seblakratupos.view.component.ComboBoxCustom cMasukSebagai;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblMasukSebagai;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsernameLogin;
    private javax.swing.JPanel leftContainer;
    private seblakratupos.view.component.PanelCustom loginContainer;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel mainPanel;
    private seblakratupos.view.component.PanelCustom panelCustom1;
    private seblakratupos.view.component.PanelCustom panelCustom2;
    private seblakratupos.view.component.PanelCustom panelCustom3;
    private javax.swing.JPanel passContainer;
    private javax.swing.JPanel passContainer1;
    private javax.swing.JPanel rightContainer;
    private javax.swing.JLabel tDetail;
    private javax.swing.JLabel tNamaToko;
    private javax.swing.JLabel txtCopyright;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JPanel usrContainer;
    // End of variables declaration//GEN-END:variables
}
