/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package seblakratupos.view;

/**
 *
 * @author Al
 */
public class PenggunaPanel extends javax.swing.JPanel {

    /**
     * Creates new form pengguna
     */
    public PenggunaPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCustomV21 = new seblakratupos.view.component.PanelCustomV2();
        panelCustomV24 = new seblakratupos.view.component.PanelCustomV2();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        buttonCustomV21 = new seblakratupos.view.component.ButtonCustomV2();
        panelCustomV23 = new seblakratupos.view.component.PanelCustomV2();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelCustomV25 = new seblakratupos.view.component.PanelCustomV2();
        panelCustomV26 = new seblakratupos.view.component.PanelCustomV2();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        panelCustomV27 = new seblakratupos.view.component.PanelCustomV2();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        panelCustomV22 = new seblakratupos.view.component.PanelCustomV2();
        panelCustomV28 = new seblakratupos.view.component.PanelCustomV2();
        jLabel13 = new javax.swing.JLabel();
        panelCustomV29 = new seblakratupos.view.component.PanelCustomV2();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        comboBoxCustom1 = new seblakratupos.view.component.ComboBoxCustom();
        jLabel18 = new javax.swing.JLabel();
        panelCustomV210 = new seblakratupos.view.component.PanelCustomV2();
        buttonCustomV25 = new seblakratupos.view.component.ButtonCustomV2();
        buttonCustomV22 = new seblakratupos.view.component.ButtonCustomV2();
        buttonCustomV24 = new seblakratupos.view.component.ButtonCustomV2();

        setBackground(new java.awt.Color(252, 249, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(14, 14, 14, 14));
        setPreferredSize(new java.awt.Dimension(1075, 639));

        panelCustomV21.setBackground(new java.awt.Color(255, 255, 255));
        panelCustomV21.setBorderColor(new java.awt.Color(231, 189, 187));
        panelCustomV21.setBorderThickness(1);

        panelCustomV24.setBackground(new java.awt.Color(255, 255, 255));
        panelCustomV24.setBorderBottomThickness(1);
        panelCustomV24.setBorderColor(new java.awt.Color(231, 189, 187));

        jLabel1.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 24)); // NOI18N
        jLabel1.setText("Daftar Pengguna");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        buttonCustomV21.setBackground(new java.awt.Color(215, 4, 39));
        buttonCustomV21.setForeground(new java.awt.Color(255, 255, 255));
        buttonCustomV21.setText("Tambah Baru");
        buttonCustomV21.setActiveBackground(new java.awt.Color(215, 4, 39));
        buttonCustomV21.setActiveBorderColor(new java.awt.Color(255, 255, 255));
        buttonCustomV21.setActiveForeground(new java.awt.Color(255, 255, 255));
        buttonCustomV21.setActiveHoverBackground(new java.awt.Color(215, 4, 39));
        buttonCustomV21.setActiveHoverBorderColor(new java.awt.Color(255, 255, 255));
        buttonCustomV21.setActiveHoverForeground(new java.awt.Color(255, 255, 255));
        buttonCustomV21.setDisabledBackground(new java.awt.Color(215, 4, 39));
        buttonCustomV21.setDisabledBorderColor(new java.awt.Color(255, 255, 255));
        buttonCustomV21.setDisabledForeground(new java.awt.Color(255, 255, 255));
        buttonCustomV21.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 16)); // NOI18N
        buttonCustomV21.setHoverBackground(new java.awt.Color(215, 4, 39));
        buttonCustomV21.setHoverForeground(new java.awt.Color(255, 255, 255));
        buttonCustomV21.setInactiveBackground(new java.awt.Color(215, 4, 39));
        buttonCustomV21.setInactiveForeground(new java.awt.Color(255, 255, 255));
        buttonCustomV21.setPressedBackground(new java.awt.Color(175, 3, 31));
        buttonCustomV21.setPressedBorderColor(new java.awt.Color(255, 255, 255));
        buttonCustomV21.setPressedForeground(new java.awt.Color(255, 255, 255));
        buttonCustomV21.setRoundBottomLeft(0);
        buttonCustomV21.setRoundBottomRight(0);
        buttonCustomV21.setRoundTopLeft(0);
        buttonCustomV21.setRoundTopRight(0);
        buttonCustomV21.addActionListener(this::buttonCustomV21ActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(buttonCustomV21, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(buttonCustomV21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout panelCustomV24Layout = new javax.swing.GroupLayout(panelCustomV24);
        panelCustomV24.setLayout(panelCustomV24Layout);
        panelCustomV24Layout.setHorizontalGroup(
            panelCustomV24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustomV24Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelCustomV24Layout.setVerticalGroup(
            panelCustomV24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelCustomV24Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        panelCustomV23.setBackground(new java.awt.Color(248, 248, 248));
        panelCustomV23.setBorderBottomThickness(1);
        panelCustomV23.setBorderColor(new java.awt.Color(231, 189, 187));

        jLabel2.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(92, 62, 60));
        jLabel2.setText("No");

        jLabel3.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(92, 62, 60));
        jLabel3.setText("Username");

        jLabel4.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(92, 62, 60));
        jLabel4.setText("Peran(role)");

        jLabel5.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(92, 62, 60));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Status");

        jLabel6.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(92, 62, 60));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Aksi");

        javax.swing.GroupLayout panelCustomV23Layout = new javax.swing.GroupLayout(panelCustomV23);
        panelCustomV23.setLayout(panelCustomV23Layout);
        panelCustomV23Layout.setHorizontalGroup(
            panelCustomV23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomV23Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(65, 65, 65)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        panelCustomV23Layout.setVerticalGroup(
            panelCustomV23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomV23Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelCustomV23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        panelCustomV25.setBackground(new java.awt.Color(255, 255, 255));
        panelCustomV25.setBorderColor(new java.awt.Color(231, 189, 187));
        panelCustomV25.setBorderThickness(1);

        panelCustomV26.setBackground(new java.awt.Color(255, 255, 255));
        panelCustomV26.setBorderBottomThickness(1);
        panelCustomV26.setBorderColor(new java.awt.Color(231, 189, 187));

        jLabel7.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(92, 62, 60));
        jLabel7.setText("1");

        jLabel9.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(24, 26, 46));
        jLabel9.setText("kasir");

        jLabel11.setBackground(new java.awt.Color(222, 222, 251));
        jLabel11.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 12)); // NOI18N
        jLabel11.setText("Kasir");

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seblakratupos/asset/icon/iconpensil.png"))); // NOI18N

        javax.swing.GroupLayout panelCustomV26Layout = new javax.swing.GroupLayout(panelCustomV26);
        panelCustomV26.setLayout(panelCustomV26Layout);
        panelCustomV26Layout.setHorizontalGroup(
            panelCustomV26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomV26Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        panelCustomV26Layout.setVerticalGroup(
            panelCustomV26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomV26Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelCustomV26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addGroup(panelCustomV26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel9)
                        .addComponent(jLabel11)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panelCustomV27.setBackground(new java.awt.Color(255, 255, 255));
        panelCustomV27.setBorderBottomThickness(1);
        panelCustomV27.setBorderColor(new java.awt.Color(231, 189, 187));

        jLabel8.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(92, 62, 60));
        jLabel8.setText("2");

        jLabel10.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(24, 26, 46));
        jLabel10.setText("owner");

        jLabel12.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 12)); // NOI18N
        jLabel12.setText("Owner");

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seblakratupos/asset/icon/iconpensil.png"))); // NOI18N

        javax.swing.GroupLayout panelCustomV27Layout = new javax.swing.GroupLayout(panelCustomV27);
        panelCustomV27.setLayout(panelCustomV27Layout);
        panelCustomV27Layout.setHorizontalGroup(
            panelCustomV27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomV27Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        panelCustomV27Layout.setVerticalGroup(
            panelCustomV27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomV27Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelCustomV27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addGroup(panelCustomV27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel10)
                        .addComponent(jLabel12)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelCustomV25Layout = new javax.swing.GroupLayout(panelCustomV25);
        panelCustomV25.setLayout(panelCustomV25Layout);
        panelCustomV25Layout.setHorizontalGroup(
            panelCustomV25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomV25Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(panelCustomV25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCustomV26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCustomV27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1))
        );
        panelCustomV25Layout.setVerticalGroup(
            panelCustomV25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomV25Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelCustomV26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelCustomV27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(382, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(panelCustomV25);

        javax.swing.GroupLayout panelCustomV21Layout = new javax.swing.GroupLayout(panelCustomV21);
        panelCustomV21.setLayout(panelCustomV21Layout);
        panelCustomV21Layout.setHorizontalGroup(
            panelCustomV21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panelCustomV21Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(panelCustomV21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCustomV24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCustomV23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1))
        );
        panelCustomV21Layout.setVerticalGroup(
            panelCustomV21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomV21Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(panelCustomV24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(panelCustomV23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1))
        );

        panelCustomV22.setBorderColor(new java.awt.Color(231, 189, 187));
        panelCustomV22.setBorderThickness(1);

        panelCustomV28.setBackground(new java.awt.Color(255, 255, 255));
        panelCustomV28.setBorderColor(new java.awt.Color(231, 189, 187));

        jLabel13.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 18)); // NOI18N
        jLabel13.setText("Tambah  Pengguna");

        javax.swing.GroupLayout panelCustomV28Layout = new javax.swing.GroupLayout(panelCustomV28);
        panelCustomV28.setLayout(panelCustomV28Layout);
        panelCustomV28Layout.setHorizontalGroup(
            panelCustomV28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomV28Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        panelCustomV28Layout.setVerticalGroup(
            panelCustomV28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomV28Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel13)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        panelCustomV29.setBackground(new java.awt.Color(255, 255, 255));
        panelCustomV29.setBorderColor(new java.awt.Color(231, 189, 187));
        panelCustomV29.setBorderThickness(1);

        jLabel14.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        jLabel14.setText("Username");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 189, 187)));

        jTextField3.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 16)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(92, 62, 60));
        jTextField3.setText("Contoh: kasir_utama");
        jTextField3.setBorder(null);
        jTextField3.setMargin(new java.awt.Insets(10, 10, 10, 6));
        jTextField3.addActionListener(this::jTextField3ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jTextField3)
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jLabel15.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        jLabel15.setText("Password Baru");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 189, 187)));
        jPanel1.setForeground(new java.awt.Color(92, 62, 60));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seblakratupos/asset/icon/IconMata.png"))); // NOI18N

        jPasswordField1.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 16)); // NOI18N
        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPasswordField1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel16.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        jLabel16.setText("Peran (Role)");

        jLabel17.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        jLabel17.setText("Status Akun");

        comboBoxCustom1.setBorder(null);
        comboBoxCustom1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kasir", "Owner" }));
        comboBoxCustom1.setBorderColor(new java.awt.Color(231, 189, 187));
        comboBoxCustom1.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 16)); // NOI18N
        comboBoxCustom1.setPopupBorderColor(new java.awt.Color(231, 189, 187));
        comboBoxCustom1.setPopupRound(0);
        comboBoxCustom1.setRound(0);
        comboBoxCustom1.setSelectionBackground(new java.awt.Color(252, 233, 232));

        jLabel18.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(92, 62, 60));
        jLabel18.setText("Kosongkan jika tidak ingin menambah password.");

        javax.swing.GroupLayout panelCustomV29Layout = new javax.swing.GroupLayout(panelCustomV29);
        panelCustomV29.setLayout(panelCustomV29Layout);
        panelCustomV29Layout.setHorizontalGroup(
            panelCustomV29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomV29Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelCustomV29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCustomV29Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustomV29Layout.createSequentialGroup()
                        .addGroup(panelCustomV29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCustomV29Layout.createSequentialGroup()
                                .addGroup(panelCustomV29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(comboBoxCustom1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(24, 24, 24))))
        );
        panelCustomV29Layout.setVerticalGroup(
            panelCustomV29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomV29Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCustomV210.setBackground(new java.awt.Color(255, 255, 255));
        panelCustomV210.setBorderColor(new java.awt.Color(231, 189, 187));
        panelCustomV210.setBorderThickness(1);
        panelCustomV210.setBorderTopThickness(0);

        buttonCustomV25.setBackground(new java.awt.Color(215, 4, 39));
        buttonCustomV25.setForeground(new java.awt.Color(255, 255, 255));
        buttonCustomV25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seblakratupos/asset/icon/IconSimpan.png"))); // NOI18N
        buttonCustomV25.setText("Simpan Perubahan");
        buttonCustomV25.setActiveBackground(new java.awt.Color(215, 4, 39));
        buttonCustomV25.setActiveBorderColor(new java.awt.Color(255, 255, 255));
        buttonCustomV25.setActiveForeground(new java.awt.Color(255, 255, 255));
        buttonCustomV25.setActiveHoverBackground(new java.awt.Color(215, 4, 39));
        buttonCustomV25.setActiveHoverBorderColor(new java.awt.Color(255, 255, 255));
        buttonCustomV25.setActiveHoverForeground(new java.awt.Color(255, 255, 255));
        buttonCustomV25.setDisabledBackground(new java.awt.Color(215, 4, 39));
        buttonCustomV25.setDisabledBorderColor(new java.awt.Color(255, 255, 255));
        buttonCustomV25.setDisabledForeground(new java.awt.Color(255, 255, 255));
        buttonCustomV25.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 16)); // NOI18N
        buttonCustomV25.setHoverBackground(new java.awt.Color(215, 4, 39));
        buttonCustomV25.setHoverForeground(new java.awt.Color(255, 255, 255));
        buttonCustomV25.setInactiveBackground(new java.awt.Color(215, 4, 39));
        buttonCustomV25.setInactiveForeground(new java.awt.Color(255, 255, 255));
        buttonCustomV25.setPressedBackground(new java.awt.Color(175, 3, 31));
        buttonCustomV25.setPressedBorderColor(new java.awt.Color(255, 255, 255));
        buttonCustomV25.setPressedForeground(new java.awt.Color(255, 255, 255));
        buttonCustomV25.setRoundBottomLeft(4);
        buttonCustomV25.setRoundBottomRight(4);
        buttonCustomV25.setRoundTopLeft(4);
        buttonCustomV25.setRoundTopRight(4);
        buttonCustomV25.addActionListener(this::buttonCustomV25ActionPerformed);

        buttonCustomV22.setBackground(new java.awt.Color(251, 248, 255));
        buttonCustomV22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seblakratupos/asset/icon/icon hapus.png"))); // NOI18N
        buttonCustomV22.setText("Hapus");
        buttonCustomV22.setActiveBackground(new java.awt.Color(251, 248, 255));
        buttonCustomV22.setActiveBorderColor(new java.awt.Color(215, 4, 39));
        buttonCustomV22.setActiveForeground(new java.awt.Color(255, 255, 255));
        buttonCustomV22.setActiveHoverBackground(new java.awt.Color(251, 248, 255));
        buttonCustomV22.setActiveHoverBorderColor(new java.awt.Color(215, 4, 39));
        buttonCustomV22.setActiveHoverForeground(new java.awt.Color(0, 0, 0));
        buttonCustomV22.setBorderThickness(1);
        buttonCustomV22.setDisabledBackground(new java.awt.Color(251, 248, 255));
        buttonCustomV22.setDisabledBorderColor(new java.awt.Color(215, 4, 39));
        buttonCustomV22.setDisabledForeground(new java.awt.Color(215, 4, 39));
        buttonCustomV22.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 16)); // NOI18N
        buttonCustomV22.setHoverBackground(new java.awt.Color(251, 248, 255));
        buttonCustomV22.setHoverBorderColor(new java.awt.Color(215, 4, 39));
        buttonCustomV22.setHoverForeground(new java.awt.Color(215, 4, 39));
        buttonCustomV22.setInactiveBackground(new java.awt.Color(251, 248, 255));
        buttonCustomV22.setInactiveBorderColor(new java.awt.Color(215, 4, 39));
        buttonCustomV22.setInactiveForeground(new java.awt.Color(215, 4, 39));
        buttonCustomV22.setPressedBackground(new java.awt.Color(237, 237, 237));
        buttonCustomV22.setPressedBorderColor(new java.awt.Color(215, 4, 39));
        buttonCustomV22.setPressedForeground(new java.awt.Color(215, 4, 39));
        buttonCustomV22.setRoundBottomLeft(4);
        buttonCustomV22.setRoundBottomRight(4);
        buttonCustomV22.setRoundTopLeft(4);
        buttonCustomV22.setRoundTopRight(4);
        buttonCustomV22.addActionListener(this::buttonCustomV22ActionPerformed);

        buttonCustomV24.setBackground(new java.awt.Color(251, 248, 255));
        buttonCustomV24.setText("Batal");
        buttonCustomV24.setActiveBackground(new java.awt.Color(251, 248, 255));
        buttonCustomV24.setActiveBorderColor(new java.awt.Color(0, 0, 0));
        buttonCustomV24.setActiveForeground(new java.awt.Color(255, 255, 255));
        buttonCustomV24.setActiveHoverBackground(new java.awt.Color(251, 248, 255));
        buttonCustomV24.setActiveHoverBorderColor(new java.awt.Color(0, 0, 0));
        buttonCustomV24.setActiveHoverForeground(new java.awt.Color(0, 0, 0));
        buttonCustomV24.setBorderThickness(1);
        buttonCustomV24.setDisabledBackground(new java.awt.Color(251, 248, 255));
        buttonCustomV24.setDisabledBorderColor(new java.awt.Color(51, 51, 51));
        buttonCustomV24.setDisabledForeground(new java.awt.Color(0, 0, 0));
        buttonCustomV24.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 16)); // NOI18N
        buttonCustomV24.setHoverBackground(new java.awt.Color(251, 248, 255));
        buttonCustomV24.setHoverBorderColor(new java.awt.Color(0, 0, 0));
        buttonCustomV24.setHoverForeground(new java.awt.Color(0, 0, 0));
        buttonCustomV24.setInactiveBackground(new java.awt.Color(251, 248, 255));
        buttonCustomV24.setInactiveBorderColor(new java.awt.Color(0, 0, 0));
        buttonCustomV24.setInactiveForeground(new java.awt.Color(0, 0, 0));
        buttonCustomV24.setPressedBackground(new java.awt.Color(237, 237, 237));
        buttonCustomV24.setPressedBorderColor(new java.awt.Color(0, 0, 0));
        buttonCustomV24.setPressedForeground(new java.awt.Color(0, 0, 0));
        buttonCustomV24.setRoundBottomLeft(4);
        buttonCustomV24.setRoundBottomRight(4);
        buttonCustomV24.setRoundTopLeft(4);
        buttonCustomV24.setRoundTopRight(4);
        buttonCustomV24.addActionListener(this::buttonCustomV24ActionPerformed);

        javax.swing.GroupLayout panelCustomV210Layout = new javax.swing.GroupLayout(panelCustomV210);
        panelCustomV210.setLayout(panelCustomV210Layout);
        panelCustomV210Layout.setHorizontalGroup(
            panelCustomV210Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomV210Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelCustomV210Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCustomV210Layout.createSequentialGroup()
                        .addComponent(buttonCustomV24, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonCustomV22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(buttonCustomV25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        panelCustomV210Layout.setVerticalGroup(
            panelCustomV210Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomV210Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(buttonCustomV25, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCustomV210Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCustomV22, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCustomV24, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelCustomV22Layout = new javax.swing.GroupLayout(panelCustomV22);
        panelCustomV22.setLayout(panelCustomV22Layout);
        panelCustomV22Layout.setHorizontalGroup(
            panelCustomV22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCustomV210, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelCustomV29, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 347, Short.MAX_VALUE)
            .addGroup(panelCustomV22Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(panelCustomV28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelCustomV22Layout.setVerticalGroup(
            panelCustomV22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomV22Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(panelCustomV28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelCustomV29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(panelCustomV210, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelCustomV21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelCustomV22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCustomV22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCustomV21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCustomV21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCustomV21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCustomV21ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void buttonCustomV25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCustomV25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCustomV25ActionPerformed

    private void buttonCustomV22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCustomV22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCustomV22ActionPerformed

    private void buttonCustomV24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCustomV24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCustomV24ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private seblakratupos.view.component.ButtonCustomV2 buttonCustomV21;
    private seblakratupos.view.component.ButtonCustomV2 buttonCustomV22;
    private seblakratupos.view.component.ButtonCustomV2 buttonCustomV24;
    private seblakratupos.view.component.ButtonCustomV2 buttonCustomV25;
    private seblakratupos.view.component.ComboBoxCustom comboBoxCustom1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private seblakratupos.view.component.PanelCustomV2 panelCustomV21;
    private seblakratupos.view.component.PanelCustomV2 panelCustomV210;
    private seblakratupos.view.component.PanelCustomV2 panelCustomV22;
    private seblakratupos.view.component.PanelCustomV2 panelCustomV23;
    private seblakratupos.view.component.PanelCustomV2 panelCustomV24;
    private seblakratupos.view.component.PanelCustomV2 panelCustomV25;
    private seblakratupos.view.component.PanelCustomV2 panelCustomV26;
    private seblakratupos.view.component.PanelCustomV2 panelCustomV27;
    private seblakratupos.view.component.PanelCustomV2 panelCustomV28;
    private seblakratupos.view.component.PanelCustomV2 panelCustomV29;
    // End of variables declaration//GEN-END:variables
}
