/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package seblakratupos.view;

/**
 *
 * @author Al
 */
public class ProdukPanel extends javax.swing.JPanel {

    /**
     * Creates new form produk
     */
    public ProdukPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelCustomV21 = new seblakratupos.view.component.PanelCustomV2();
        panelCustomV59 = new seblakratupos.view.component.PanelCustomV2();
        jLabel1 = new javax.swing.JLabel();
        buttonCustomV21 = new seblakratupos.view.component.ButtonCustomV2();
        buttonCustomV25 = new seblakratupos.view.component.ButtonCustomV2();
        buttonCustomV26 = new seblakratupos.view.component.ButtonCustomV2();
        buttonCustomV27 = new seblakratupos.view.component.ButtonCustomV2();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCustom1 = new seblakratupos.view.component.TableCustom();
        panelCustomV22 = new seblakratupos.view.component.PanelCustomV2();
        panelCustomV27 = new seblakratupos.view.component.PanelCustomV2();
        jLabel12 = new javax.swing.JLabel();
        panelCustomV28 = new seblakratupos.view.component.PanelCustomV2();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        panelCustomV210 = new seblakratupos.view.component.PanelCustomV2();
        buttonCustomV29 = new seblakratupos.view.component.ButtonCustomV2();
        buttonCustomV22 = new seblakratupos.view.component.ButtonCustomV2();
        buttonCustomV24 = new seblakratupos.view.component.ButtonCustomV2();

        setBackground(new java.awt.Color(252, 249, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(14, 14, 14, 14));

        panelCustomV21.setBorderColor(new java.awt.Color(231, 189, 187));
        panelCustomV21.setBorderThickness(1);
        panelCustomV21.setPreferredSize(new java.awt.Dimension(688, 481));

        panelCustomV59.setBackground(new java.awt.Color(255, 255, 255));
        panelCustomV59.setBorderBottomThickness(1);
        panelCustomV59.setBorderColor(new java.awt.Color(231, 189, 187));
        panelCustomV59.setRoundBottomLeft(3);
        panelCustomV59.setRoundBottomRight(3);
        panelCustomV59.setRoundTopLeft(3);
        panelCustomV59.setRoundTopRight(3);

        jLabel1.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(24, 26, 46));
        jLabel1.setText("Daftar Menu");
        jLabel1.setMaximumSize(new java.awt.Dimension(198, 31));
        jLabel1.setMinimumSize(new java.awt.Dimension(198, 31));
        jLabel1.setName(""); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(198, 31));

        buttonCustomV21.setBackground(new java.awt.Color(215, 4, 39));
        buttonCustomV21.setForeground(new java.awt.Color(255, 255, 255));
        buttonCustomV21.setText("Tambah Baru");
        buttonCustomV21.setActiveBackground(new java.awt.Color(215, 4, 39));
        buttonCustomV21.setActiveBorderColor(new java.awt.Color(255, 255, 255));
        buttonCustomV21.setActiveForeground(new java.awt.Color(255, 255, 255));
        buttonCustomV21.setActiveHoverBackground(new java.awt.Color(215, 4, 39));
        buttonCustomV21.setActiveHoverBorderColor(new java.awt.Color(255, 255, 255));
        buttonCustomV21.setActiveHoverForeground(new java.awt.Color(255, 255, 255));
        buttonCustomV21.setDisabledBackground(new java.awt.Color(215, 4, 39));
        buttonCustomV21.setDisabledBorderColor(new java.awt.Color(255, 255, 255));
        buttonCustomV21.setDisabledForeground(new java.awt.Color(255, 255, 255));
        buttonCustomV21.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 16)); // NOI18N
        buttonCustomV21.setHoverBackground(new java.awt.Color(215, 4, 39));
        buttonCustomV21.setHoverForeground(new java.awt.Color(255, 255, 255));
        buttonCustomV21.setInactiveBackground(new java.awt.Color(215, 4, 39));
        buttonCustomV21.setInactiveForeground(new java.awt.Color(255, 255, 255));
        buttonCustomV21.setPressedBackground(new java.awt.Color(175, 3, 31));
        buttonCustomV21.setPressedBorderColor(new java.awt.Color(255, 255, 255));
        buttonCustomV21.setPressedForeground(new java.awt.Color(255, 255, 255));
        buttonCustomV21.setRoundBottomLeft(0);
        buttonCustomV21.setRoundBottomRight(0);
        buttonCustomV21.setRoundTopLeft(0);
        buttonCustomV21.setRoundTopRight(0);
        buttonCustomV21.addActionListener(this::buttonCustomV21ActionPerformed);

        buttonCustomV25.setText("Semua");
        buttonCustomV25.setActiveBackground(new java.awt.Color(255, 255, 255));
        buttonCustomV25.setActiveBorderColor(new java.awt.Color(173, 0, 28));
        buttonCustomV25.setActiveForeground(new java.awt.Color(173, 0, 28));
        buttonCustomV25.setActiveHoverBackground(new java.awt.Color(255, 255, 255));
        buttonCustomV25.setActiveHoverBorderColor(new java.awt.Color(173, 0, 28));
        buttonCustomV25.setActiveHoverForeground(new java.awt.Color(173, 0, 28));
        buttonCustomV25.setBorderBottomThickness(3);
        buttonCustomV25.setDisabledForeground(new java.awt.Color(92, 62, 60));
        buttonCustomV25.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        buttonCustomV25.setHoverBackground(new java.awt.Color(255, 255, 255));
        buttonCustomV25.setHoverForeground(new java.awt.Color(92, 62, 60));
        buttonCustomV25.setIconTextGap(0);
        buttonCustomV25.setInactiveForeground(new java.awt.Color(92, 62, 60));
        buttonCustomV25.setPaddingBottom(15);
        buttonCustomV25.setPaddingLeft(0);
        buttonCustomV25.setPaddingRight(0);
        buttonCustomV25.setPaddingTop(0);
        buttonCustomV25.setPressedBackground(new java.awt.Color(255, 255, 255));
        buttonCustomV25.setPressedBorderColor(new java.awt.Color(173, 0, 28));
        buttonCustomV25.setPressedForeground(new java.awt.Color(173, 0, 28));
        buttonCustomV25.setRoundBottomLeft(0);
        buttonCustomV25.setRoundBottomRight(0);
        buttonCustomV25.setRoundTopLeft(0);
        buttonCustomV25.setRoundTopRight(0);

        buttonCustomV26.setText("Seblak");
        buttonCustomV26.setActiveBackground(new java.awt.Color(255, 255, 255));
        buttonCustomV26.setActiveBorderColor(new java.awt.Color(173, 0, 28));
        buttonCustomV26.setActiveForeground(new java.awt.Color(173, 0, 28));
        buttonCustomV26.setActiveHoverBackground(new java.awt.Color(255, 255, 255));
        buttonCustomV26.setActiveHoverBorderColor(new java.awt.Color(173, 0, 28));
        buttonCustomV26.setActiveHoverForeground(new java.awt.Color(173, 0, 28));
        buttonCustomV26.setBorderBottomThickness(3);
        buttonCustomV26.setDisabledForeground(new java.awt.Color(92, 62, 60));
        buttonCustomV26.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        buttonCustomV26.setHoverBackground(new java.awt.Color(255, 255, 255));
        buttonCustomV26.setHoverForeground(new java.awt.Color(92, 62, 60));
        buttonCustomV26.setIconTextGap(0);
        buttonCustomV26.setInactiveForeground(new java.awt.Color(92, 62, 60));
        buttonCustomV26.setPaddingBottom(15);
        buttonCustomV26.setPaddingLeft(0);
        buttonCustomV26.setPaddingRight(0);
        buttonCustomV26.setPaddingTop(0);
        buttonCustomV26.setPressedBackground(new java.awt.Color(255, 255, 255));
        buttonCustomV26.setPressedBorderColor(new java.awt.Color(173, 0, 28));
        buttonCustomV26.setPressedForeground(new java.awt.Color(173, 0, 28));
        buttonCustomV26.setRoundBottomLeft(0);
        buttonCustomV26.setRoundBottomRight(0);
        buttonCustomV26.setRoundTopLeft(0);
        buttonCustomV26.setRoundTopRight(0);
        buttonCustomV26.addActionListener(this::buttonCustomV26ActionPerformed);

        buttonCustomV27.setText("Minuman");
        buttonCustomV27.setActiveBackground(new java.awt.Color(255, 255, 255));
        buttonCustomV27.setActiveBorderColor(new java.awt.Color(173, 0, 28));
        buttonCustomV27.setActiveForeground(new java.awt.Color(173, 0, 28));
        buttonCustomV27.setActiveHoverBackground(new java.awt.Color(255, 255, 255));
        buttonCustomV27.setActiveHoverBorderColor(new java.awt.Color(173, 0, 28));
        buttonCustomV27.setActiveHoverForeground(new java.awt.Color(173, 0, 28));
        buttonCustomV27.setBorderBottomThickness(3);
        buttonCustomV27.setDisabledForeground(new java.awt.Color(92, 62, 60));
        buttonCustomV27.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        buttonCustomV27.setHoverBackground(new java.awt.Color(255, 255, 255));
        buttonCustomV27.setHoverForeground(new java.awt.Color(92, 62, 60));
        buttonCustomV27.setIconTextGap(0);
        buttonCustomV27.setInactiveForeground(new java.awt.Color(92, 62, 60));
        buttonCustomV27.setPaddingBottom(15);
        buttonCustomV27.setPaddingLeft(0);
        buttonCustomV27.setPaddingRight(0);
        buttonCustomV27.setPaddingTop(0);
        buttonCustomV27.setPressedBackground(new java.awt.Color(255, 255, 255));
        buttonCustomV27.setPressedBorderColor(new java.awt.Color(173, 0, 28));
        buttonCustomV27.setPressedForeground(new java.awt.Color(173, 0, 28));
        buttonCustomV27.setRoundBottomLeft(0);
        buttonCustomV27.setRoundBottomRight(0);
        buttonCustomV27.setRoundTopLeft(0);
        buttonCustomV27.setRoundTopRight(0);

        javax.swing.GroupLayout panelCustomV59Layout = new javax.swing.GroupLayout(panelCustomV59);
        panelCustomV59.setLayout(panelCustomV59Layout);
        panelCustomV59Layout.setHorizontalGroup(
            panelCustomV59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomV59Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelCustomV59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCustomV59Layout.createSequentialGroup()
                        .addComponent(buttonCustomV25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonCustomV26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonCustomV27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelCustomV59Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(buttonCustomV21, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        panelCustomV59Layout.setVerticalGroup(
            panelCustomV59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomV59Layout.createSequentialGroup()
                .addGroup(panelCustomV59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelCustomV59Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(buttonCustomV21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCustomV59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCustomV25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCustomV26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCustomV27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1))
        );

        tableCustom1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"M001", "Es Jeruk", "Minuman", "Rp 4.000", "Tersedia"},
                {"M002", "Es Teh", "Minuman", "Rp 3.000", "Tersedia"},
                {"S001", "Seblak Original", "Seblak", "Rp 9.000", "Tersedia"}
            },
            new String [] {
                "ID", "Nama Produk", "Kategori", "Harga Jual", "Status"
            }
        ));
        tableCustom1.setCellPaddingLeft(25);
        tableCustom1.setCenterColumns("2,3,4");
        tableCustom1.setColumnWidths("70,200,110,110,110");
        tableCustom1.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        tableCustom1.setGridColor(new java.awt.Color(231, 189, 187));
        tableCustom1.setHeaderBorderColor(new java.awt.Color(231, 189, 187));
        tableCustom1.setHeaderPaddingLeft(25);
        tableCustom1.setOuterBorderThickness(0);
        tableCustom1.setRowBorderColor(new java.awt.Color(231, 189, 187));
        jScrollPane2.setViewportView(tableCustom1);

        javax.swing.GroupLayout panelCustomV21Layout = new javax.swing.GroupLayout(panelCustomV21);
        panelCustomV21.setLayout(panelCustomV21Layout);
        panelCustomV21Layout.setHorizontalGroup(
            panelCustomV21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomV21Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(panelCustomV21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCustomV59, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(1, 1, 1))
        );
        panelCustomV21Layout.setVerticalGroup(
            panelCustomV21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomV21Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(panelCustomV59, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2)
                .addGap(1, 1, 1))
        );

        panelCustomV22.setBorderColor(new java.awt.Color(231, 189, 187));
        panelCustomV22.setBorderRightThickness(1);
        panelCustomV22.setBorderThickness(1);
        panelCustomV22.setPreferredSize(new java.awt.Dimension(347, 611));

        panelCustomV27.setBorderColor(new java.awt.Color(231, 189, 187));
        panelCustomV27.setBorderThickness(1);

        jLabel12.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 1, 18)); // NOI18N
        jLabel12.setText("Tambah  Produk");

        javax.swing.GroupLayout panelCustomV27Layout = new javax.swing.GroupLayout(panelCustomV27);
        panelCustomV27.setLayout(panelCustomV27Layout);
        panelCustomV27Layout.setHorizontalGroup(
            panelCustomV27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomV27Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCustomV27Layout.setVerticalGroup(
            panelCustomV27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomV27Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        panelCustomV28.setBorderColor(new java.awt.Color(231, 189, 187));
        panelCustomV28.setBorderThickness(1);
        panelCustomV28.setBorderTopThickness(0);

        jLabel13.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        jLabel13.setText("Nama Produk");

        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 189, 187)));

        jLabel14.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        jLabel14.setText("Deskripsi");

        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 189, 187)));

        jLabel15.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        jLabel15.setText("Kategori");

        jLabel16.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        jLabel16.setText("Harga Jual");

        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 189, 187)));

        jLabel17.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        jLabel17.setText("Status Ketersedian");

        jLabel18.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        jLabel18.setText("Matikan jika stok bahan habis");

        jLabel19.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Rp");
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 189, 187)));

        jComboBox1.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Minuman", "Topping", "Seblak", " " }));

        javax.swing.GroupLayout panelCustomV28Layout = new javax.swing.GroupLayout(panelCustomV28);
        panelCustomV28.setLayout(panelCustomV28Layout);
        panelCustomV28Layout.setHorizontalGroup(
            panelCustomV28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomV28Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelCustomV28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelCustomV28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelCustomV28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCustomV28Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        panelCustomV28Layout.setVerticalGroup(
            panelCustomV28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomV28Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCustomV28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCustomV210.setBackground(new java.awt.Color(255, 255, 255));
        panelCustomV210.setBorderColor(new java.awt.Color(231, 189, 187));
        panelCustomV210.setBorderThickness(1);
        panelCustomV210.setBorderTopThickness(0);

        buttonCustomV29.setBackground(new java.awt.Color(215, 4, 39));
        buttonCustomV29.setForeground(new java.awt.Color(255, 255, 255));
        buttonCustomV29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seblakratupos/asset/icon/IconSimpan.png"))); // NOI18N
        buttonCustomV29.setText("Simpan Perubahan");
        buttonCustomV29.setActiveBackground(new java.awt.Color(215, 4, 39));
        buttonCustomV29.setActiveBorderColor(new java.awt.Color(255, 255, 255));
        buttonCustomV29.setActiveForeground(new java.awt.Color(255, 255, 255));
        buttonCustomV29.setActiveHoverBackground(new java.awt.Color(215, 4, 39));
        buttonCustomV29.setActiveHoverBorderColor(new java.awt.Color(255, 255, 255));
        buttonCustomV29.setActiveHoverForeground(new java.awt.Color(255, 255, 255));
        buttonCustomV29.setDisabledBackground(new java.awt.Color(215, 4, 39));
        buttonCustomV29.setDisabledBorderColor(new java.awt.Color(255, 255, 255));
        buttonCustomV29.setDisabledForeground(new java.awt.Color(255, 255, 255));
        buttonCustomV29.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 16)); // NOI18N
        buttonCustomV29.setHoverBackground(new java.awt.Color(215, 4, 39));
        buttonCustomV29.setHoverForeground(new java.awt.Color(255, 255, 255));
        buttonCustomV29.setInactiveBackground(new java.awt.Color(215, 4, 39));
        buttonCustomV29.setInactiveForeground(new java.awt.Color(255, 255, 255));
        buttonCustomV29.setPressedBackground(new java.awt.Color(175, 3, 31));
        buttonCustomV29.setPressedBorderColor(new java.awt.Color(255, 255, 255));
        buttonCustomV29.setPressedForeground(new java.awt.Color(255, 255, 255));
        buttonCustomV29.setRoundBottomLeft(4);
        buttonCustomV29.setRoundBottomRight(4);
        buttonCustomV29.setRoundTopLeft(4);
        buttonCustomV29.setRoundTopRight(4);
        buttonCustomV29.addActionListener(this::buttonCustomV29ActionPerformed);

        buttonCustomV22.setBackground(new java.awt.Color(251, 248, 255));
        buttonCustomV22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seblakratupos/asset/icon/icon hapus.png"))); // NOI18N
        buttonCustomV22.setText("Hapus");
        buttonCustomV22.setActiveBackground(new java.awt.Color(251, 248, 255));
        buttonCustomV22.setActiveBorderColor(new java.awt.Color(215, 4, 39));
        buttonCustomV22.setActiveForeground(new java.awt.Color(255, 255, 255));
        buttonCustomV22.setActiveHoverBackground(new java.awt.Color(251, 248, 255));
        buttonCustomV22.setActiveHoverBorderColor(new java.awt.Color(215, 4, 39));
        buttonCustomV22.setActiveHoverForeground(new java.awt.Color(0, 0, 0));
        buttonCustomV22.setBorderThickness(1);
        buttonCustomV22.setDisabledBackground(new java.awt.Color(251, 248, 255));
        buttonCustomV22.setDisabledBorderColor(new java.awt.Color(215, 4, 39));
        buttonCustomV22.setDisabledForeground(new java.awt.Color(215, 4, 39));
        buttonCustomV22.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 16)); // NOI18N
        buttonCustomV22.setHoverBackground(new java.awt.Color(251, 248, 255));
        buttonCustomV22.setHoverBorderColor(new java.awt.Color(215, 4, 39));
        buttonCustomV22.setHoverForeground(new java.awt.Color(215, 4, 39));
        buttonCustomV22.setInactiveBackground(new java.awt.Color(251, 248, 255));
        buttonCustomV22.setInactiveBorderColor(new java.awt.Color(215, 4, 39));
        buttonCustomV22.setInactiveForeground(new java.awt.Color(215, 4, 39));
        buttonCustomV22.setPressedBackground(new java.awt.Color(237, 237, 237));
        buttonCustomV22.setPressedBorderColor(new java.awt.Color(215, 4, 39));
        buttonCustomV22.setPressedForeground(new java.awt.Color(215, 4, 39));
        buttonCustomV22.setRoundBottomLeft(4);
        buttonCustomV22.setRoundBottomRight(4);
        buttonCustomV22.setRoundTopLeft(4);
        buttonCustomV22.setRoundTopRight(4);
        buttonCustomV22.addActionListener(this::buttonCustomV22ActionPerformed);

        buttonCustomV24.setBackground(new java.awt.Color(251, 248, 255));
        buttonCustomV24.setText("Batal");
        buttonCustomV24.setActiveBackground(new java.awt.Color(251, 248, 255));
        buttonCustomV24.setActiveBorderColor(new java.awt.Color(0, 0, 0));
        buttonCustomV24.setActiveForeground(new java.awt.Color(255, 255, 255));
        buttonCustomV24.setActiveHoverBackground(new java.awt.Color(251, 248, 255));
        buttonCustomV24.setActiveHoverBorderColor(new java.awt.Color(0, 0, 0));
        buttonCustomV24.setActiveHoverForeground(new java.awt.Color(0, 0, 0));
        buttonCustomV24.setBorderThickness(1);
        buttonCustomV24.setDisabledBackground(new java.awt.Color(251, 248, 255));
        buttonCustomV24.setDisabledBorderColor(new java.awt.Color(51, 51, 51));
        buttonCustomV24.setDisabledForeground(new java.awt.Color(0, 0, 0));
        buttonCustomV24.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 16)); // NOI18N
        buttonCustomV24.setHoverBackground(new java.awt.Color(251, 248, 255));
        buttonCustomV24.setHoverBorderColor(new java.awt.Color(0, 0, 0));
        buttonCustomV24.setHoverForeground(new java.awt.Color(0, 0, 0));
        buttonCustomV24.setInactiveBackground(new java.awt.Color(251, 248, 255));
        buttonCustomV24.setInactiveBorderColor(new java.awt.Color(0, 0, 0));
        buttonCustomV24.setInactiveForeground(new java.awt.Color(0, 0, 0));
        buttonCustomV24.setPressedBackground(new java.awt.Color(237, 237, 237));
        buttonCustomV24.setPressedBorderColor(new java.awt.Color(0, 0, 0));
        buttonCustomV24.setPressedForeground(new java.awt.Color(0, 0, 0));
        buttonCustomV24.setRoundBottomLeft(4);
        buttonCustomV24.setRoundBottomRight(4);
        buttonCustomV24.setRoundTopLeft(4);
        buttonCustomV24.setRoundTopRight(4);
        buttonCustomV24.addActionListener(this::buttonCustomV24ActionPerformed);

        javax.swing.GroupLayout panelCustomV210Layout = new javax.swing.GroupLayout(panelCustomV210);
        panelCustomV210.setLayout(panelCustomV210Layout);
        panelCustomV210Layout.setHorizontalGroup(
            panelCustomV210Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomV210Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelCustomV210Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCustomV210Layout.createSequentialGroup()
                        .addComponent(buttonCustomV24, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonCustomV22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(buttonCustomV29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        panelCustomV210Layout.setVerticalGroup(
            panelCustomV210Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomV210Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(buttonCustomV29, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCustomV210Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCustomV22, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCustomV24, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelCustomV22Layout = new javax.swing.GroupLayout(panelCustomV22);
        panelCustomV22.setLayout(panelCustomV22Layout);
        panelCustomV22Layout.setHorizontalGroup(
            panelCustomV22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCustomV27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelCustomV28, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustomV22Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelCustomV210, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        panelCustomV22Layout.setVerticalGroup(
            panelCustomV22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomV22Layout.createSequentialGroup()
                .addComponent(panelCustomV27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCustomV28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 16, Short.MAX_VALUE)
                .addComponent(panelCustomV210, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelCustomV21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelCustomV22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCustomV22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelCustomV21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCustomV26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCustomV26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCustomV26ActionPerformed

    private void buttonCustomV21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCustomV21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCustomV21ActionPerformed

    private void buttonCustomV29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCustomV29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCustomV29ActionPerformed

    private void buttonCustomV22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCustomV22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCustomV22ActionPerformed

    private void buttonCustomV24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCustomV24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCustomV24ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private seblakratupos.view.component.ButtonCustomV2 buttonCustomV21;
    private seblakratupos.view.component.ButtonCustomV2 buttonCustomV22;
    private seblakratupos.view.component.ButtonCustomV2 buttonCustomV24;
    private seblakratupos.view.component.ButtonCustomV2 buttonCustomV25;
    private seblakratupos.view.component.ButtonCustomV2 buttonCustomV26;
    private seblakratupos.view.component.ButtonCustomV2 buttonCustomV27;
    private seblakratupos.view.component.ButtonCustomV2 buttonCustomV29;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private seblakratupos.view.component.PanelCustomV2 panelCustomV21;
    private seblakratupos.view.component.PanelCustomV2 panelCustomV210;
    private seblakratupos.view.component.PanelCustomV2 panelCustomV22;
    private seblakratupos.view.component.PanelCustomV2 panelCustomV27;
    private seblakratupos.view.component.PanelCustomV2 panelCustomV28;
    private seblakratupos.view.component.PanelCustomV2 panelCustomV59;
    private seblakratupos.view.component.TableCustom tableCustom1;
    // End of variables declaration//GEN-END:variables
}
