/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package seblakratupos.view;

/**
 *
 * @author Al
 */
public class StokPanel extends javax.swing.JPanel {

    /**
     * Creates new form stok
     */
    public StokPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCustomV21 = new seblakratupos.view.component.PanelCustomV2();
        panelCustomV24 = new seblakratupos.view.component.PanelCustomV2();
        lblDaftarStok = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnTambahPengguna = new seblakratupos.view.component.ButtonCustomV2();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPanelStok = new seblakratupos.view.component.TableCustom();
        panelCustomV22 = new seblakratupos.view.component.PanelCustomV2();
        panelCustomV31 = new seblakratupos.view.component.PanelCustomV2();
        lblTambahStok = new javax.swing.JLabel();
        panelCustomV29 = new seblakratupos.view.component.PanelCustomV2();
        lblNamaBahan = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtNamaBahan = new javax.swing.JTextField();
        lblJumlahStokMasuk = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtJumlah = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        txtSatuan = new javax.swing.JTextField();
        lblHargaSatuan = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtHarga = new javax.swing.JTextField();
        panelCustomV210 = new seblakratupos.view.component.PanelCustomV2();
        btnSimpan = new seblakratupos.view.component.ButtonCustomV2();
        btnHapus = new seblakratupos.view.component.ButtonCustomV2();
        btnBatal = new seblakratupos.view.component.ButtonCustomV2();

        setBackground(new java.awt.Color(252, 249, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(14, 14, 14, 14));
        setPreferredSize(new java.awt.Dimension(1075, 639));

        panelCustomV21.setBackground(new java.awt.Color(255, 255, 255));
        panelCustomV21.setBorderColor(new java.awt.Color(231, 189, 187));
        panelCustomV21.setBorderThickness(1);

        panelCustomV24.setBackground(new java.awt.Color(255, 255, 255));
        panelCustomV24.setBorderBottomThickness(1);
        panelCustomV24.setBorderColor(new java.awt.Color(231, 189, 187));

        lblDaftarStok.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 24)); // NOI18N
        lblDaftarStok.setText("Daftar Stok");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnTambahPengguna.setBackground(new java.awt.Color(215, 4, 39));
        btnTambahPengguna.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahPengguna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seblakratupos/asset/icon/IconPlus.png"))); // NOI18N
        btnTambahPengguna.setText("Tambah Baru");
        btnTambahPengguna.setActiveBackground(new java.awt.Color(215, 4, 39));
        btnTambahPengguna.setActiveBorderColor(new java.awt.Color(255, 255, 255));
        btnTambahPengguna.setActiveForeground(new java.awt.Color(255, 255, 255));
        btnTambahPengguna.setActiveHoverBackground(new java.awt.Color(215, 4, 39));
        btnTambahPengguna.setActiveHoverBorderColor(new java.awt.Color(255, 255, 255));
        btnTambahPengguna.setActiveHoverForeground(new java.awt.Color(255, 255, 255));
        btnTambahPengguna.setDisabledBackground(new java.awt.Color(215, 4, 39));
        btnTambahPengguna.setDisabledBorderColor(new java.awt.Color(255, 255, 255));
        btnTambahPengguna.setDisabledForeground(new java.awt.Color(255, 255, 255));
        btnTambahPengguna.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 16)); // NOI18N
        btnTambahPengguna.setHoverBackground(new java.awt.Color(215, 4, 39));
        btnTambahPengguna.setHoverForeground(new java.awt.Color(255, 255, 255));
        btnTambahPengguna.setInactiveBackground(new java.awt.Color(215, 4, 39));
        btnTambahPengguna.setInactiveForeground(new java.awt.Color(255, 255, 255));
        btnTambahPengguna.setPressedBackground(new java.awt.Color(175, 3, 31));
        btnTambahPengguna.setPressedBorderColor(new java.awt.Color(255, 255, 255));
        btnTambahPengguna.setPressedForeground(new java.awt.Color(255, 255, 255));
        btnTambahPengguna.setRoundBottomLeft(0);
        btnTambahPengguna.setRoundBottomRight(0);
        btnTambahPengguna.setRoundTopLeft(0);
        btnTambahPengguna.setRoundTopRight(0);
        btnTambahPengguna.addActionListener(this::btnTambahPenggunaActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnTambahPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(btnTambahPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout panelCustomV24Layout = new javax.swing.GroupLayout(panelCustomV24);
        panelCustomV24.setLayout(panelCustomV24Layout);
        panelCustomV24Layout.setHorizontalGroup(
            panelCustomV24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustomV24Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblDaftarStok, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelCustomV24Layout.setVerticalGroup(
            panelCustomV24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDaftarStok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelCustomV24Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        tblPanelStok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Cabai Rawit Merah", "3", "Kilogram(Kg)"},
                {"Bawang Merah", "2", "Kilogram(Kg)"},
                {"Kencur", "1", "Kilogram(Kg)"},
                {"Garam", "5", "Bungkus"},
                {"Penyedap Rasa", "8", "Bungkus"},
                {"Kaldu Bubuk", "6", "Bungkus"},
                {"Saus Sambal", "4", "Botol"}
            },
            new String [] {
                "Nama Bahan", "Stok", "Satuan"
            }
        ));
        tblPanelStok.setCellPaddingLeft(25);
        tblPanelStok.setCenterColumns("2,3");
        tblPanelStok.setColumnWidths("240,50,80,");
        tblPanelStok.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        tblPanelStok.setGridColor(new java.awt.Color(231, 189, 187));
        tblPanelStok.setHeaderBorderColor(new java.awt.Color(231, 189, 187));
        tblPanelStok.setHeaderPaddingLeft(25);
        tblPanelStok.setOuterBorderThickness(0);
        tblPanelStok.setRowBorderColor(new java.awt.Color(231, 189, 187));
        tblPanelStok.addActionListener(this::tblPanelStokActionPerformed);
        jScrollPane1.setViewportView(tblPanelStok);

        javax.swing.GroupLayout panelCustomV21Layout = new javax.swing.GroupLayout(panelCustomV21);
        panelCustomV21.setLayout(panelCustomV21Layout);
        panelCustomV21Layout.setHorizontalGroup(
            panelCustomV21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomV21Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(panelCustomV21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCustomV24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(1, 1, 1))
        );
        panelCustomV21Layout.setVerticalGroup(
            panelCustomV21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomV21Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(panelCustomV24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        panelCustomV22.setBorderColor(new java.awt.Color(231, 189, 187));
        panelCustomV22.setBorderThickness(1);

        panelCustomV31.setBackground(new java.awt.Color(255, 255, 255));
        panelCustomV31.setBorderColor(new java.awt.Color(231, 189, 187));
        panelCustomV31.setPreferredSize(new java.awt.Dimension(345, 62));

        lblTambahStok.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 18)); // NOI18N
        lblTambahStok.setText("Tambah Stok Bahan");

        javax.swing.GroupLayout panelCustomV31Layout = new javax.swing.GroupLayout(panelCustomV31);
        panelCustomV31.setLayout(panelCustomV31Layout);
        panelCustomV31Layout.setHorizontalGroup(
            panelCustomV31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomV31Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTambahStok, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );
        panelCustomV31Layout.setVerticalGroup(
            panelCustomV31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomV31Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTambahStok)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panelCustomV29.setBackground(new java.awt.Color(255, 255, 255));
        panelCustomV29.setBorderColor(new java.awt.Color(231, 189, 187));
        panelCustomV29.setBorderThickness(1);

        lblNamaBahan.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        lblNamaBahan.setText("Nama Bahan");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 189, 187)));

        txtNamaBahan.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 16)); // NOI18N
        txtNamaBahan.setForeground(new java.awt.Color(92, 62, 60));
        txtNamaBahan.setText("Contoh: Cabai Rawit Merah");
        txtNamaBahan.setBorder(null);
        txtNamaBahan.setMargin(new java.awt.Insets(10, 10, 10, 6));
        txtNamaBahan.addActionListener(this::txtNamaBahanActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(txtNamaBahan, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(txtNamaBahan, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        lblJumlahStokMasuk.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        lblJumlahStokMasuk.setText("Jumlah Stok Masuk");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 189, 187)));
        jPanel1.setForeground(new java.awt.Color(92, 62, 60));

        txtJumlah.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 16)); // NOI18N
        txtJumlah.setText("0");
        txtJumlah.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtJumlah, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 189, 187)));

        txtSatuan.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 16)); // NOI18N
        txtSatuan.setText("Kilogram (Kg)");
        txtSatuan.setBorder(null);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(txtSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(txtSatuan)
                .addGap(0, 0, 0))
        );

        lblHargaSatuan.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        lblHargaSatuan.setText("Harga Satuan");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 189, 187)));

        txtHarga.setBorder(null);
        txtHarga.addActionListener(this::txtHargaActionPerformed);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout panelCustomV29Layout = new javax.swing.GroupLayout(panelCustomV29);
        panelCustomV29.setLayout(panelCustomV29Layout);
        panelCustomV29Layout.setHorizontalGroup(
            panelCustomV29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomV29Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelCustomV29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHargaSatuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelCustomV29Layout.createSequentialGroup()
                        .addComponent(lblNamaBahan, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustomV29Layout.createSequentialGroup()
                        .addGroup(panelCustomV29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblJumlahStokMasuk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCustomV29Layout.createSequentialGroup()
                                .addGroup(panelCustomV29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCustomV29Layout.createSequentialGroup()
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(24, 24, 24))
                    .addGroup(panelCustomV29Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelCustomV29Layout.setVerticalGroup(
            panelCustomV29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomV29Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblNamaBahan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblJumlahStokMasuk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCustomV29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(lblHargaSatuan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCustomV210.setBackground(new java.awt.Color(255, 255, 255));
        panelCustomV210.setBorderColor(new java.awt.Color(231, 189, 187));
        panelCustomV210.setBorderThickness(1);
        panelCustomV210.setBorderTopThickness(0);

        btnSimpan.setBackground(new java.awt.Color(215, 4, 39));
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seblakratupos/asset/icon/IconSimpan.png"))); // NOI18N
        btnSimpan.setText("Simpan Perubahan");
        btnSimpan.setActiveBackground(new java.awt.Color(215, 4, 39));
        btnSimpan.setActiveBorderColor(new java.awt.Color(255, 255, 255));
        btnSimpan.setActiveForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setActiveHoverBackground(new java.awt.Color(215, 4, 39));
        btnSimpan.setActiveHoverBorderColor(new java.awt.Color(255, 255, 255));
        btnSimpan.setActiveHoverForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setDisabledBackground(new java.awt.Color(215, 4, 39));
        btnSimpan.setDisabledBorderColor(new java.awt.Color(255, 255, 255));
        btnSimpan.setDisabledForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 16)); // NOI18N
        btnSimpan.setHoverBackground(new java.awt.Color(215, 4, 39));
        btnSimpan.setHoverForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setInactiveBackground(new java.awt.Color(215, 4, 39));
        btnSimpan.setInactiveForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setPressedBackground(new java.awt.Color(175, 3, 31));
        btnSimpan.setPressedBorderColor(new java.awt.Color(255, 255, 255));
        btnSimpan.setPressedForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setRoundBottomLeft(4);
        btnSimpan.setRoundBottomRight(4);
        btnSimpan.setRoundTopLeft(4);
        btnSimpan.setRoundTopRight(4);
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);

        btnHapus.setBackground(new java.awt.Color(251, 248, 255));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seblakratupos/asset/icon/icon hapus.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.setActiveBackground(new java.awt.Color(251, 248, 255));
        btnHapus.setActiveBorderColor(new java.awt.Color(215, 4, 39));
        btnHapus.setActiveForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setActiveHoverBackground(new java.awt.Color(251, 248, 255));
        btnHapus.setActiveHoverBorderColor(new java.awt.Color(215, 4, 39));
        btnHapus.setActiveHoverForeground(new java.awt.Color(0, 0, 0));
        btnHapus.setBorderThickness(1);
        btnHapus.setDisabledBackground(new java.awt.Color(251, 248, 255));
        btnHapus.setDisabledBorderColor(new java.awt.Color(215, 4, 39));
        btnHapus.setDisabledForeground(new java.awt.Color(215, 4, 39));
        btnHapus.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 16)); // NOI18N
        btnHapus.setHoverBackground(new java.awt.Color(251, 248, 255));
        btnHapus.setHoverBorderColor(new java.awt.Color(215, 4, 39));
        btnHapus.setHoverForeground(new java.awt.Color(215, 4, 39));
        btnHapus.setInactiveBackground(new java.awt.Color(251, 248, 255));
        btnHapus.setInactiveBorderColor(new java.awt.Color(215, 4, 39));
        btnHapus.setInactiveForeground(new java.awt.Color(215, 4, 39));
        btnHapus.setPressedBackground(new java.awt.Color(237, 237, 237));
        btnHapus.setPressedBorderColor(new java.awt.Color(215, 4, 39));
        btnHapus.setPressedForeground(new java.awt.Color(215, 4, 39));
        btnHapus.setRoundBottomLeft(4);
        btnHapus.setRoundBottomRight(4);
        btnHapus.setRoundTopLeft(4);
        btnHapus.setRoundTopRight(4);
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        btnBatal.setBackground(new java.awt.Color(251, 248, 255));
        btnBatal.setText("Batal");
        btnBatal.setActiveBackground(new java.awt.Color(251, 248, 255));
        btnBatal.setActiveBorderColor(new java.awt.Color(0, 0, 0));
        btnBatal.setActiveForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setActiveHoverBackground(new java.awt.Color(251, 248, 255));
        btnBatal.setActiveHoverBorderColor(new java.awt.Color(0, 0, 0));
        btnBatal.setActiveHoverForeground(new java.awt.Color(0, 0, 0));
        btnBatal.setBorderThickness(1);
        btnBatal.setDisabledBackground(new java.awt.Color(251, 248, 255));
        btnBatal.setDisabledBorderColor(new java.awt.Color(51, 51, 51));
        btnBatal.setDisabledForeground(new java.awt.Color(0, 0, 0));
        btnBatal.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 16)); // NOI18N
        btnBatal.setHoverBackground(new java.awt.Color(251, 248, 255));
        btnBatal.setHoverBorderColor(new java.awt.Color(0, 0, 0));
        btnBatal.setHoverForeground(new java.awt.Color(0, 0, 0));
        btnBatal.setInactiveBackground(new java.awt.Color(251, 248, 255));
        btnBatal.setInactiveBorderColor(new java.awt.Color(0, 0, 0));
        btnBatal.setInactiveForeground(new java.awt.Color(0, 0, 0));
        btnBatal.setPressedBackground(new java.awt.Color(237, 237, 237));
        btnBatal.setPressedBorderColor(new java.awt.Color(0, 0, 0));
        btnBatal.setPressedForeground(new java.awt.Color(0, 0, 0));
        btnBatal.setRoundBottomLeft(4);
        btnBatal.setRoundBottomRight(4);
        btnBatal.setRoundTopLeft(4);
        btnBatal.setRoundTopRight(4);
        btnBatal.addActionListener(this::btnBatalActionPerformed);

        javax.swing.GroupLayout panelCustomV210Layout = new javax.swing.GroupLayout(panelCustomV210);
        panelCustomV210.setLayout(panelCustomV210Layout);
        panelCustomV210Layout.setHorizontalGroup(
            panelCustomV210Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomV210Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelCustomV210Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCustomV210Layout.createSequentialGroup()
                        .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                    .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        panelCustomV210Layout.setVerticalGroup(
            panelCustomV210Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomV210Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCustomV210Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelCustomV22Layout = new javax.swing.GroupLayout(panelCustomV22);
        panelCustomV22.setLayout(panelCustomV22Layout);
        panelCustomV22Layout.setHorizontalGroup(
            panelCustomV22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCustomV210, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelCustomV22Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(panelCustomV31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(panelCustomV29, javax.swing.GroupLayout.PREFERRED_SIZE, 347, Short.MAX_VALUE)
        );
        panelCustomV22Layout.setVerticalGroup(
            panelCustomV22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomV22Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(panelCustomV31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelCustomV29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(panelCustomV210, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelCustomV21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelCustomV22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCustomV22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCustomV21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaBahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaBahanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaBahanActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBatalActionPerformed

    private void tblPanelStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblPanelStokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblPanelStokActionPerformed

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    private void btnTambahPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahPenggunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahPenggunaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private seblakratupos.view.component.ButtonCustomV2 btnBatal;
    private seblakratupos.view.component.ButtonCustomV2 btnHapus;
    private seblakratupos.view.component.ButtonCustomV2 btnSimpan;
    private seblakratupos.view.component.ButtonCustomV2 btnTambahPengguna;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDaftarStok;
    private javax.swing.JLabel lblHargaSatuan;
    private javax.swing.JLabel lblJumlahStokMasuk;
    private javax.swing.JLabel lblNamaBahan;
    private javax.swing.JLabel lblTambahStok;
    private seblakratupos.view.component.PanelCustomV2 panelCustomV21;
    private seblakratupos.view.component.PanelCustomV2 panelCustomV210;
    private seblakratupos.view.component.PanelCustomV2 panelCustomV22;
    private seblakratupos.view.component.PanelCustomV2 panelCustomV24;
    private seblakratupos.view.component.PanelCustomV2 panelCustomV29;
    private seblakratupos.view.component.PanelCustomV2 panelCustomV31;
    private seblakratupos.view.component.TableCustom tblPanelStok;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtNamaBahan;
    private javax.swing.JTextField txtSatuan;
    // End of variables declaration//GEN-END:variables
}
