/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package seblakratupos.view.layout.main;

/**
 *
 * @author Al
 */
public class transaksi extends javax.swing.JPanel {

    /**
     * Creates new form transaksi
     */
    public transaksi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCustomV21 = new seblakratupos.view.component.PanelCustomV2();
        pDaftarMenu = new seblakratupos.view.component.PanelCustomV2();
        panelCustomV22 = new seblakratupos.view.component.PanelCustomV2();
        jLabel1 = new javax.swing.JLabel();
        buttonCustomV21 = new seblakratupos.view.component.ButtonCustomV2();
        pKostumisasi = new seblakratupos.view.component.PanelCustomV2();
        pKeranjang = new seblakratupos.view.component.PanelCustomV2();

        javax.swing.GroupLayout panelCustomV21Layout = new javax.swing.GroupLayout(panelCustomV21);
        panelCustomV21.setLayout(panelCustomV21Layout);
        panelCustomV21Layout.setHorizontalGroup(
            panelCustomV21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelCustomV21Layout.setVerticalGroup(
            panelCustomV21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(252, 249, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(14, 14, 14, 14));
        setPreferredSize(new java.awt.Dimension(1075, 639));
        setLayout(new java.awt.GridLayout(1, 3, 17, 17));

        pDaftarMenu.setBackground(new java.awt.Color(255, 255, 255));
        pDaftarMenu.setBorderColor(new java.awt.Color(231, 189, 187));
        pDaftarMenu.setBorderThickness(1);
        pDaftarMenu.setRoundBottomLeft(3);
        pDaftarMenu.setRoundBottomRight(3);
        pDaftarMenu.setRoundTopLeft(3);
        pDaftarMenu.setRoundTopRight(3);

        panelCustomV22.setBackground(new java.awt.Color(255, 255, 255));
        panelCustomV22.setBorderBottomThickness(1);
        panelCustomV22.setBorderColor(new java.awt.Color(231, 189, 187));
        panelCustomV22.setRoundBottomLeft(3);
        panelCustomV22.setRoundBottomRight(3);
        panelCustomV22.setRoundTopLeft(3);
        panelCustomV22.setRoundTopRight(3);

        jLabel1.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 18)); // NOI18N
        jLabel1.setText("Daftar Menu");

        buttonCustomV21.setText("Semua");
        buttonCustomV21.setActiveBackground(new java.awt.Color(255, 255, 255));
        buttonCustomV21.setActiveHoverBackground(new java.awt.Color(255, 255, 255));
        buttonCustomV21.setBorderBottomThickness(3);
        buttonCustomV21.setDisabledForeground(new java.awt.Color(92, 62, 60));
        buttonCustomV21.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        buttonCustomV21.setHoverBackground(new java.awt.Color(255, 255, 255));
        buttonCustomV21.setHoverForeground(new java.awt.Color(92, 62, 60));
        buttonCustomV21.setIconTextGap(0);
        buttonCustomV21.setInactiveForeground(new java.awt.Color(92, 62, 60));
        buttonCustomV21.setPaddingBottom(15);
        buttonCustomV21.setPaddingLeft(0);
        buttonCustomV21.setPaddingRight(0);
        buttonCustomV21.setPaddingTop(0);
        buttonCustomV21.setPressedBackground(new java.awt.Color(255, 255, 255));
        buttonCustomV21.setRoundBottomLeft(0);
        buttonCustomV21.setRoundBottomRight(0);
        buttonCustomV21.setRoundTopLeft(0);
        buttonCustomV21.setRoundTopRight(0);

        javax.swing.GroupLayout panelCustomV22Layout = new javax.swing.GroupLayout(panelCustomV22);
        panelCustomV22.setLayout(panelCustomV22Layout);
        panelCustomV22Layout.setHorizontalGroup(
            panelCustomV22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomV22Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelCustomV22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCustomV22Layout.createSequentialGroup()
                        .addComponent(buttonCustomV21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelCustomV22Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                        .addGap(16, 16, 16))))
        );
        panelCustomV22Layout.setVerticalGroup(
            panelCustomV22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomV22Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15)
                .addComponent(buttonCustomV21, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );

        javax.swing.GroupLayout pDaftarMenuLayout = new javax.swing.GroupLayout(pDaftarMenu);
        pDaftarMenu.setLayout(pDaftarMenuLayout);
        pDaftarMenuLayout.setHorizontalGroup(
            pDaftarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDaftarMenuLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(panelCustomV22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
        pDaftarMenuLayout.setVerticalGroup(
            pDaftarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDaftarMenuLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(panelCustomV22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(526, Short.MAX_VALUE))
        );

        add(pDaftarMenu);

        pKostumisasi.setBackground(new java.awt.Color(255, 255, 255));
        pKostumisasi.setBorderColor(new java.awt.Color(231, 189, 187));
        pKostumisasi.setBorderThickness(1);
        pKostumisasi.setRoundBottomLeft(3);
        pKostumisasi.setRoundBottomRight(3);
        pKostumisasi.setRoundTopLeft(3);
        pKostumisasi.setRoundTopRight(3);

        javax.swing.GroupLayout pKostumisasiLayout = new javax.swing.GroupLayout(pKostumisasi);
        pKostumisasi.setLayout(pKostumisasiLayout);
        pKostumisasiLayout.setHorizontalGroup(
            pKostumisasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 337, Short.MAX_VALUE)
        );
        pKostumisasiLayout.setVerticalGroup(
            pKostumisasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
        );

        add(pKostumisasi);

        pKeranjang.setBackground(new java.awt.Color(255, 255, 255));
        pKeranjang.setBorderColor(new java.awt.Color(231, 189, 187));
        pKeranjang.setBorderThickness(1);
        pKeranjang.setRoundBottomLeft(3);
        pKeranjang.setRoundBottomRight(3);
        pKeranjang.setRoundTopLeft(3);
        pKeranjang.setRoundTopRight(3);

        javax.swing.GroupLayout pKeranjangLayout = new javax.swing.GroupLayout(pKeranjang);
        pKeranjang.setLayout(pKeranjangLayout);
        pKeranjangLayout.setHorizontalGroup(
            pKeranjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 337, Short.MAX_VALUE)
        );
        pKeranjangLayout.setVerticalGroup(
            pKeranjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
        );

        add(pKeranjang);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private seblakratupos.view.component.ButtonCustomV2 buttonCustomV21;
    private javax.swing.JLabel jLabel1;
    private seblakratupos.view.component.PanelCustomV2 pDaftarMenu;
    private seblakratupos.view.component.PanelCustomV2 pKeranjang;
    private seblakratupos.view.component.PanelCustomV2 pKostumisasi;
    private seblakratupos.view.component.PanelCustomV2 panelCustomV21;
    private seblakratupos.view.component.PanelCustomV2 panelCustomV22;
    // End of variables declaration//GEN-END:variables
}
